export const minimumNumberOfKeystrokes = {
    "my watch fell in the water. ": 27,
"prevailing wind from the east. ": 30,
"never too rich and never too thin. ": 34,
"breathing is difficult. ": 23,
"I can see the rings on Saturn. ": 30,
"physics and chemistry are hard. ": 31,
"my bank account is overdrawn. ": 29,
"elections bring out the best. ": 29,
"we are having spaghetti. ": 24,
"time to go shopping. ": 20,
"a problem with the engine. ": 26,
"elephants are afraid of mice. ": 29,
"my favorite place to visit. ": 27,
"three two one zero blast off. ": 29,
"my favorite subject is psychology. ": 34,
"circumstances are unacceptable. ": 31,
"watch out for low flying objects. ": 33,
"if at first you do not succeed. ": 31,
"please provide your date of birth. ": 34,
"we run the risk of failure. ": 27,
"prayer in schools offends some. ": 31,
"he is just like everyone else. ": 30,
"great disturbance in the force. ": 31,
"love means many things. ": 23,
"you must be getting old. ": 24,
"the world is a stage. ": 21,
"can I skate with sister today. ": 30,
"neither a borrower nor a lender be. ": 35,
"one heck of a question. ": 23,
"question that must be answered. ": 31,
"beware the ides of March. ": 25,
"double double toil and trouble. ": 31,
"the power of denial. ": 20,
"I agree with you. ": 17,
"do not say anything. ": 20,
"play it again Sam. ": 18,
"the force is with you. ": 22,
"you are not a jedi yet. ": 23,
"an offer you cannot refuse. ": 27,
"are you talking to me. ": 22,
"yes you are very smart. ": 23,
"all work and no play. ": 21,
"hair gel is very greasy. ": 24,
"Valium in the economy size. ": 27,
"the facts get in the way. ": 25,
"the dreamers of dreams. ": 23,
"did you have a good time. ": 25,
"space is a high priority. ": 25,
"you are a wonderful example. ": 28,
"do not squander your time. ": 26,
"do not drink too much. ": 22,
"take a coffee break. ": 20,
"popularity is desired by all. ": 29,
"the music is better than it sounds. ": 35,
"starlight and dewdrop. ": 22,
"the living is easy. ": 19,
"fish are jumping. ": 17,
"the cotton is high. ": 19,
"drove my chevy to the levee. ": 28,
"but the levee was dry. ": 22,
"I took the rover from the shop. ": 31,
"movie about a nutty professor. ": 30,
"come and see our new car. ": 25,
"coming up with killer sound bites. ": 34,
"I am going to a music lesson. ": 29,
"the opposing team is over there. ": 32,
"soon we will return from the city. ": 34,
"I am wearing a tie and a jacket. ": 32,
"the quick brown fox jumped. ": 27,
"all together in one big pile. ": 29,
"wear a crown with many jewels. ": 30,
"there will be some fog tonight. ": 31,
"I am allergic to bees and peanuts. ": 34,
"he is still on our team. ": 24,
"the dow jones index has risen. ": 30,
"my preferred treat is chocolate. ": 32,
"the king sends you to the tower. ": 32,
"we are subjects and must obey. ": 30,
"mom made her a turtleneck. ": 26,
"goldilocks and the three bears. ": 31,
"we went grocery shopping. ": 25,
"the assignment is due today. ": 28,
"what you see is what you get. ": 29,
"for your information only. ": 26,
"a quarter of a century. ": 23,
"the store will close at ten. ": 28,
"head shoulders knees and toes. ": 30,
"vanilla flavored ice cream. ": 27,
"frequently asked questions. ": 27,
"round robin scheduling. ": 23,
"information super highway. ": 26,
"my favorite web browser. ": 24,
"the laser printer is jammed. ": 28,
"all good boys deserve fudge. ": 28,
"the second largest country. ": 27,
"call for more details. ": 22,
"just in time for the party. ": 27,
"have a good weekend. ": 20,
"video camera with a zoom lens. ": 30,
"what a monkey sees a monkey will do. ": 36,
"that is very unfortunate. ": 25,
"the back yard of our house. ": 27,
"this is a very good idea. ": 25,
"reading week is just about here. ": 32,
"our fax number has changed. ": 27,
"thank you for your help. ": 24,
"no exchange without a bill. ": 27,
"the early bird gets the worm. ": 29,
"buckle up for safety. ": 21,
"this is too much to handle. ": 27,
"protect your environment. ": 25,
"world population is growing. ": 28,
"the library is closed today. ": 28,
"Mary had a little lamb. ": 23,
"teaching services will help. ": 28,
"we accept personal checks. ": 26,
"this is a non profit organization. ": 34,
"user friendly interface. ": 24,
"healthy food is good for you. ": 29,
"hands on experience with a job. ": 31,
"this watch is too expensive. ": 28,
"the postal service is very slow. ": 32,
"communicate through email. ": 26,
"the capital of our nation. ": 26,
"travel at the speed of light. ": 29,
"I do not fully agree with you. ": 30,
"gas bills are sent monthly. ": 27,
"earth quakes are predictable. ": 29,
"life is but a dream. ": 20,
"take it to the recycling depot. ": 31,
"sent this by registered mail. ": 29,
"fall is my favorite season. ": 27,
"a fox is a very smart animal. ": 29,
"the kids are very excited. ": 26,
"parking lot is full of trucks. ": 30,
"my bike has a flat tire. ": 24,
"do not walk too quickly. ": 24,
"a duck quacks to ask for food. ": 30,
"limited warranty of two years. ": 30,
"the four seasons will come. ": 27,
"the sun rises in the east. ": 26,
"it is very windy today. ": 23,
"do not worry about this. ": 24,
"dashing through the snow. ": 25,
"want to join us for lunch. ": 26,
"stay away from strangers. ": 25,
"accompanied by an adult. ": 24,
"see you later alligator. ": 24,
"make my day you sucker. ": 23,
"I can play much better now. ": 27,
"she wears too much makeup. ": 26,
"my bare face in the wind. ": 25,
"batman wears a cape. ": 20,
"I hate baking pies. ": 19,
"lydia wants to go home. ": 23,
"win first prize in the contest. ": 31,
"freud wrote of the ego. ": 23,
"I do not care if you do that. ": 29,
"always cover all the bases. ": 27,
"nobody cares anymore. ": 21,
"can we play cards tonight. ": 26,
"get rid of that immediately. ": 28,
"I watched blazing saddles. ": 26,
"the sum of the parts. ": 21,
"they love to yap about nothing. ": 31,
"peek out the window. ": 20,
"be home before midnight. ": 24,
"he played a pimp in that movie. ": 31,
"I skimmed through your proposal. ": 32,
"he was wearing a sweatshirt. ": 28,
"no more war no more bloodshed. ": 30,
"toss the ball around. ": 21,
"I will meet you at noon. ": 24,
"I want to hold your hand. ": 25,
"the children are playing. ": 25,
"superman never wore a mask. ": 27,
"I listen to the tape everyday. ": 30,
"he is shouting loudly. ": 22,
"correct your diction immediately. ": 33,
"seasoned golfers love the game. ": 31,
"he cooled off after she left. ": 29,
"my dog sheds his hair. ": 22,
"join us on the patio. ": 21,
"these cookies are so amazing. ": 29,
"I can still feel your presence. ": 31,
"the dog will bite you. ": 22,
"a most ridiculous thing. ": 24,
"where did you get that tie. ": 27,
"what a lovely red jacket. ": 25,
"do you like to shop on Sunday. ": 30,
"I spilled coffee on the carpet. ": 31,
"the largest of the five oceans. ": 31,
"shall we play a round of cards. ": 31,
"olympic athletes use drugs. ": 27,
"my mother makes good cookies. ": 29,
"do a good deed to someone. ": 26,
"quick there is someone knocking. ": 32,
"flashing red light means stop. ": 30,
"sprawling subdivisions are bad. ": 31,
"where did I leave my glasses. ": 29,
"on the way to the cottage. ": 26,
"a lot of chlorine in the water. ": 31,
"do not drink the water. ": 23,
"my car always breaks in the winter. ": 35,
"santa claus got stuck. ": 22,
"public transit is much faster. ": 30,
"zero in on the facts. ": 21,
"make up a few more phrases. ": 27,
"my fingers are very cold. ": 25,
"rain rain go away. ": 18,
"bad for the environment. ": 24,
"universities are too expensive. ": 31,
"the price of gas is high. ": 25,
"the winner of the race. ": 23,
"we drive on parkways. ": 21,
"we park in driveways. ": 21,
"go out for some pizza and beer. ": 31,
"effort is what it will take. ": 28,
"where can my little dog be. ": 27,
"if you were not so stupid. ": 26,
"not quite so smart as you think. ": 32,
"do you like to go camping. ": 26,
"this person is a disaster. ": 26,
"the imagination of the nation. ": 30,
"universally understood to be wrong. ": 35,
"listen to five hours of opera. ": 30,
"an occasional taste of chocolate. ": 33,
"victims deserve more redress. ": 29,
"the protesters blocked all traffic. ": 35,
"the acceptance speech was boring. ": 33,
"work hard to reach the summit. ": 30,
"a little encouragement is needed. ": 33,
"stiff penalty for staying out late. ": 35,
"the pen is mightier than the sword. ": 35,
"exceed the maximum speed limit. ": 31,
"in sharp contrast to your words. ": 32,
"this leather jacket is too warm. ": 32,
"consequences of a wrong turn. ": 29,
"this mission statement is baloney. ": 34,
"you will loose your voice. ": 26,
"every apple from every tree. ": 28,
"are you sure you want this. ": 27,
"the fourth edition was better. ": 30,
"this system of taxation. ": 24,
"beautiful paintings in the gallery. ": 35,
"a yard is almost as a meter. ": 28,
"we missed your birthday. ": 24,
"coalition governments never work. ": 33,
"destruction of the rain forest. ": 31,
"I like to play tennis. ": 22,
"acutely aware of her good looks. ": 32,
"you want to eat your cake. ": 26,
"machinery is too complicated. ": 29,
"a glance in the right direction. ": 32,
"I just cannot figure this out. ": 30,
"please follow the guidelines. ": 29,
"an airport is a very busy place. ": 32,
"mystery of the lost lagoon. ": 27,
"is there any indication of this. ": 32,
"the chamber makes important decisions. ": 38,
"this phenomenon will never occur. ": 33,
"obligations must be met first. ": 30,
"valid until the end of the year. ": 32,
"file all complaints in writing. ": 31,
"tickets are very expensive. ": 27,
"a picture is worth many words. ": 30,
"this camera takes nice photographs. ": 35,
"it looks like a shack. ": 22,
"the dog buried the bone. ": 24,
"the daring young man. ": 21,
"this equation is too complicated. ": 33,
"express delivery is very fast. ": 30,
"I will put on my glasses. ": 25,
"a touchdown in the last minute. ": 31,
"the treasury department is broke. ": 33,
"a good response to the question. ": 32,
"well connected with people. ": 27,
"the bathroom is good for reading. ": 33,
"the generation gap gets wider. ": 30,
"chemical spill took forever. ": 28,
"prepare for the exam in advance. ": 32,
"interesting observation was made. ": 33,
"bank transaction was not registered. ": 36,
"your etiquette needs some work. ": 31,
"we better investigate this. ": 27,
"stability of the nation. ": 24,
"house with new electrical panel. ": 32,
"our silver anniversary is coming. ": 33,
"the presidential suite is very busy. ": 36,
"the punishment should fit the crime. ": 36,
"sharp cheese keeps the mind sharp. ": 34,
"the registration period is over. ": 32,
"you have my sympathy. ": 21,
"the objective of the exercise. ": 30,
"historic meeting without a result. ": 34,
"very reluctant to enter. ": 24,
"good at addition and subtraction. ": 33,
"six daughters and seven sons. ": 29,
"a thoroughly disgusting thing to say. ": 37,
"sign the withdrawal slip. ": 25,
"relations are very strained. ": 28,
"the minimum amount of time. ": 27,
"a very traditional way to dress. ": 32,
"the aspirations of a nation. ": 28,
"medieval times were very hard. ": 30,
"a security force of eight thousand. ": 35,
"there are winners and losers. ": 29,
"the voters turfed him out. ": 26,
"pay off a mortgage for a house. ": 31,
"the collapse of the Roman empire. ": 33,
"did you see that spectacular explosion. ": 39,
"keep receipts for all your expenses. ": 36,
"the assault took six months. ": 28,
"get your priorities in order. ": 29,
"traveling requires a lot of fuel. ": 33,
"longer than a football field. ": 29,
"a good joke deserves a good laugh. ": 34,
"the union will go on strike. ": 28,
"never mix religion and politics. ": 32,
"interactions between men and women. ": 35,
"where did you get such a silly idea. ": 36,
"it should be sunny tomorrow. ": 28,
"a psychiatrist will help you. ": 29,
"you should visit a doctor. ": 26,
"you must make an appointment. ": 29,
"the fax machine is broken. ": 26,
"players must know all the rules. ": 32,
"a dog is the best friend of a man. ": 34,
"would you like to come to my house. ": 35,
"February has an extra day. ": 26,
"do not feel too bad about it. ": 29,
"this library has many books. ": 28,
"construction makes traveling difficult. ": 39,
"he called seven times. ": 22,
"that is a very odd question. ": 28,
"a feeling of complete exasperation. ": 35,
"we must redouble our efforts. ": 29,
"no kissing in the library. ": 26,
"that agreement is rife with problems. ": 37,
"vote according to your conscience. ": 34,
"my favourite sport is racketball. ": 33,
"sad to hear that news. ": 22,
"the gun discharged by accident. ": 31,
"one of the poorest nations. ": 27,
"the algorithm is too complicated. ": 33,
"your presentation was inspiring. ": 32,
"that land is owned by the government. ": 37,
"burglars never leave their business card. ": 41,
"the fire blazed all weekend. ": 28,
"if diplomacy does not work. ": 27,
"please keep this confidential. ": 30,
"the rationale behind the decision. ": 34,
"the cat has a pleasant temperament. ": 35,
"our housekeeper does a thorough job. ": 36,
"her majesty visited our country. ": 32,
"handicapped persons need consideration. ": 39,
"these barracks are big enough. ": 30,
"sing the gospel and the blues. ": 30,
"he underwent triple bypass surgery. ": 35,
"the ropes of a new organization. ": 32,
"peering through a small hole. ": 29,
"rapidly running short on words. ": 31,
"it is difficult to concentrate. ": 31,
"give me one spoonful of coffee. ": 31,
"two or three cups of coffee. ": 28,
"just like it says on the can good. ": 34,
"companies announce a merger. ": 28,
"electric cars need big fuel cells. ": 34,
"the plug does not fit the socket. ": 33,
"drugs should be avoided. ": 24,
"the most beautiful sunset. ": 26,
"we dine out on the weekends. ": 28,
"get aboard the ship is leaving. ": 31,
"the water was monitored daily. ": 30,
"he watched in astonishment. ": 27,
"a big scratch on the tabletop. ": 30,
"salesmen must make their monthly quota. ": 39,
"saving that child was an heroic effort. ": 39,
"granite is the hardest of all rocks. ": 36,
"bring the offenders to justice. ": 31,
"every Saturday he folds the laundry. ": 36,
"careless driving results in a fine. ": 35,
"microscopes make small things look big. ": 39,
"a coupon for a free sample. ": 27,
"fine but only in moderation. ": 28,
"a subject one can really enjoy. ": 31,
"important for political parties. ": 32,
"that sticker needs to be validated. ": 35,
"the fire raged for an entire month. ": 35,
"one never takes too many precautions. ": 37,
"we have enough witnesses. ": 25,
"labour unions know how to organize. ": 35,
"people blow their horn a lot. ": 29,
"a correction had to be published. ": 33,
"I like baroque and classical music. ": 35,
"the proprietor was unavailable. ": 31,
"be discreet about your meeting. ": 31,
"meet tomorrow in the lavatory. ": 30,
"suburbs are sprawling up everywhere. ": 36,
"shivering is one way to keep warm. ": 34,
"dolphins leap high out of the water. ": 36,
"try to enjoy your maternity leave. ": 34,
"the ventilation system is broken. ": 33,
"dinosaurs have been extinct for ages. ": 37,
"an inefficient way to heat a house. ": 35,
"the bus was very crowded. ": 25,
"an injustice is committed every day. ": 36,
"the coronation was very exciting. ": 33,
"look in the syllabus for the course. ": 36,
"rectangular objects have four sides. ": 36,
"prescription drugs require a note. ": 34,
"the insulation is not working. ": 30,
"nothing finer than discovering a treasure. ": 42,
"our life expectancy has increased. ": 34,
"the cream rises to the top. ": 27,
"the high waves will swamp us. ": 29,
"the treasurer must balance her books. ": 37,
"completely sold out of that. ": 28,
"the location of the crime. ": 26,
"the chancellor was very boring. ": 31,
"the accident scene is a shrine for fans. ": 40,
"a tumor is OK provided it is benign. ": 36,
"please take a bath this month. ": 30,
"rent is paid at the beginning of the month. ": 43,
"for murder you get a long prison sentence. ": 42,
"a much higher risk of getting cancer. ": 37,
"quit while you are ahead. ": 25,
"knee bone is connected to the thigh bone. ": 41,
"safe to walk the streets in the evening. ": 40,
"luckily my wallet was found. ": 28,
"one hour is allotted for questions. ": 35,
"so you think you deserve a raise. ": 33,
"they watched the entire movie. ": 30,
"good jobs for those with education. ": 35,
"jumping right out of the water. ": 31,
"the trains are always late. ": 27,
"sit at the front of the bus. ": 28,
"do you prefer a window seat. ": 28,
"the food at this restaurant. ": 28,
"Canada has ten provinces. ": 25,
"the elevator door appears to be stuck. ": 38,
"raindrops keep falling on my head. ": 34,
"spill coffee on the carpet. ": 27,
"an excellent way to communicate. ": 32,
"with each step forward. ": 23,
"faster than a speeding bullet. ": 30,
"wishful thinking is fine. ": 25,
"nothing wrong with his style. ": 29,
"arguing with the boss is futile. ": 32,
"taking the train is usually faster. ": 35,
"what goes up must come down. ": 28,
"be persistent to win a strike. ": 30,
"presidents drive expensive cars. ": 32,
"the stock exchange dipped. ": 26,
"why do you ask silly questions. ": 31,
"that is a very nasty cut. ": 25,
"what to do when the oil runs dry. ": 33,
"learn to walk before you run. ": 29,
"insurance is important for bad drivers. ": 39,
"traveling to conferences is fun. ": 32,
"do you get nervous when you speak. ": 34,
"pumping helps if the roads are slippery. ": 40,
"parking tickets can be challenged. ": 34,
"apartments are too expensive. ": 29,
"find a nearby parking spot. ": 27,
"gun powder must be handled with care. ": 37,
"just what the doctor ordered. ": 29,
"a rattle snake is very poisonous. ": 33,
"weeping willows are found near water. ": 37,
"I cannot believe I ate the whole thing. ": 39,
"the biggest hamburger I have ever seen. ": 39,
"gamblers eventually loose their shirts. ": 39,
"exercise is good for the mind. ": 30,
"irregular verbs are the hardest to learn. ": 41,
"they might find your comment offensive. ": 39,
"tell a lie and your nose will grow. ": 35,
"an enlarged nose suggests you are a liar. ": 41,
"lie detector tests never work. ": 30,
"do not lie in court or else. ": 28,
"most judges are very honest. ": 28,
"only an idiot would lie in court. ": 33,
"important news always seems to be late. ": 39,
"please try to be home before midnight. ": 38,
"if you come home late the doors are locked. ": 43,
"dormitory doors are locked at midnight. ": 39,
"staying up all night is a bad idea. ": 35,
"you are a capitalist pig. ": 25,
"motivational seminars make me sick. ": 35,
"questioning the wisdom of the courts. ": 37,
"rejection letters are discouraging. ": 35,
"the first time he tried to swim. ": 32,
"that referendum asked a silly question. ": 39,
"a steep learning curve in riding a unicycle. ": 44,
"a good stimulus deserves a good response. ": 41,
"everybody looses in custody battles. ": 36,
"put garbage in an abandoned mine. ": 33,
"employee recruitment takes a lot of effort. ": 43,
"experience is hard to come by. ": 30,
"everyone wants to win the lottery. ": 34,
"the picket line gives me the chills. ": 36,
}