export const minimumNumberOfKeystrokes = {
    "my watch fell in the water and sank to the bottom. ": 39,
    "there is a prevailing wind from the east. ": 33,
    "never too rich and never too thin. ": 27,
    "so much pollution that breathing is difficult. ": 39,
    "with my telescope I can see the rings on Saturn. ": 38,
    "physics and chemistry are for the birds. ": 33,
    "my bank account appears to be overdrawn. ": 33,
    "elections bring out the best in politicians. ": 37,
    "for dinner we are having spaghetti and meatballs. ": 41,
    "it is time to go grocery shopping. ": 27,
    "there seems to be a problem with the engine. ": 35,
    "is it true that elephants are afraid of mice. ": 36,
    "the zoo is one of my favorite places to visit. ": 36,
    "five four three two one zero blast off. ": 31,
    "my favorite subject is psychology. ": 29,
    "these circumstances are completely unacceptable. ": 43,
    "watch out for low flying objects. ": 27,
    "if at first you do not succeed try try again. ": 35,
    "please provide your sex and date of birth. ": 34,
    "if we do not succeed we run the risk of failure. ": 37,
    "prayer in public schools is not agreeable to all. ": 40,
    "he is just like everyone else except better. ": 36,
    "there is great disturbance in the force. ": 33,
    "love means never having to say you are sorry. ": 36,
    "you have grey hair so you must be getting old. ": 36,
    "the world is a stage and we are the players. ": 34,
    "Mom can I ice skate with sister today. ": 30,
    "neither a borrower nor a lender be. ": 28,
    "to be or not to be is one heck of a question. ": 33,
    "that is the question that must be answered. ": 35,
    "beware the ides of March come and go quickly. ": 36,
    "who said double double toil and trouble. ": 33,
    "never underestimate the power of denial. ": 34,
    "I would agree with you if you were right. ": 32,
    "do not say anything at all about this subject. ": 37,
    "play it again Sam was never spoken in the movie. ": 38,
    "the Force is with you young Skywalker. ": 31,
    "you are not a Jedi yet but keep practicing. ": 34,
    "I will make you an offer you cannot refuse. ": 34,
    "if you are talking to me then please speak up. ": 36,
    "yes you are very smart now shut up. ": 27,
    "all work and no play make jack a dull boy. ": 32,
    "that hair gel is very greasy. ": 23,
    "Valium in the convenient economy size. ": 32,
    "never let the facts get in the way of the truth. ": 37,
    "we are the dreamers of dreams. ": 24,
    "did you have a good time on your vacation. ": 33,
    "space is a high priority for our apartment. ": 35,
    "you are a wonderful example to all students. ": 36,
    "do not squander your time on video games. ": 33,
    "if you drink too much you will get drunk. ": 32,
    "Lipton employees take coffee breaks. ": 31,
    "popularity is kind of like Tupperware. ": 32,
    "the music of Wagner is better than it sounds. ": 36,
    "starlight and dewdrop are waiting for thee. ": 36,
    "it is summertime and the living is easy. ": 32,
    "fish are jumping and the cotton is high. ": 32,
    "drove my Chevy to the levee but the levee was dry. ": 39,
    "helter skelter in a summer swelter. ": 29,
    "I took the rover from the shop. ": 24,
    "did you see that movie about the nutty professor. ": 40,
    "you must come over and see our new car. ": 30,
    "coming up with killer sound bites. ": 28,
    "I am going to a music lesson this afternoon. ": 35,
    "the opposing team is over there. ": 26,
    "hold on to this until we return from the city. ": 36,
    "I am wearing a tie and a jacket. ": 24,
    "the quick brown fox jumped over the lazy dogs. ": 37,
    "lump them all together in one big pile. ": 31,
    "I will wear a crown with many jewels. ": 29,
    "there will be some fog tonight. ": 25,
    "I am allergic to bees and peanuts. ": 27,
    "friend or foe he is still on our team. ": 29,
    "the Dow Jones index has reached a new high. ": 34,
    "my preferred treat is a chocolate bar. ": 31,
    "it is not the king that sends you to the Tower. ": 36,
    "we are subjects of the queen and must obey. ": 34,
    "Mom made her a turtleneck for the winter. ": 33,
    "Goldilocks and the three bears had a lot of fun. ": 38,
    "we did some grocery shopping yesterday. ": 33,
    "the assignment is due today at midnight. ": 33,
    "what you see is what you get. ": 22,
    "this is for your information only. ": 28,
    "a quarter of a century is about enough. ": 31,
    "the store will close at ten this evening. ": 33,
    "head shoulders knees and toes. ": 25,
    "vanilla flavored ice cream is the best. ": 32,
    "frequently asked questions are easy. ": 31,
    "round robin scheduling of exams. ": 27,
    "information super highway is a dream. ": 31,
    "my favorite web browser is Netscape. ": 30,
    "the laser printer is jammed with paper. ": 32,
    "all good boys deserve fudge and cake. ": 30,
    "the second largest country is Canada. ": 31,
    "call for more details when you are ready. ": 33,
    "she arrived just in time for the party. ": 31,
    "have a good weekend and take care. ": 27,
    "video camera with a zoom and macro lens. ": 32,
    "what a monkey sees a monkey will do. ": 28,
    "that is very unfortunate about your mother. ": 36,
    "the back yard of our house is very spacious. ": 35,
    "this is a very good idea about nothing. ": 31,
    "the March reading week is just about here. ": 34,
    "our fax number has changed to the new area code. ": 38,
    "thank you for your help with my assignment. ": 35,
    "no exchange without proof of purchase. ": 32,
    "the early bird gets the worm most of the time. ": 36,
    "buckle up for safety when you drive in a car. ": 35,
    "this is too much to handle just now. ": 28,
    "protect your environment by recycling. ": 33,
    "the world population is growing too fast. ": 34,
    "the library is closed today but open tomorrow. ": 38,
    "Mary had a little lamb as the saying goes. ": 33,
    "teaching services will help with classes. ": 35,
    "we accept personal cheques from anyone. ": 33,
    "this non profit organization is for charity. ": 37,
    "user friendly interface is a good idea. ": 32,
    "eat healthy food and you will endure. ": 30,
    "get some hands on experience with a job. ": 32,
    "this watch is too expensive but I like it. ": 33,
    "United States postal service is very slow. ": 35,
    "communicate through email if you prefer. ": 34,
    "the capital of our nation is Ottawa. ": 29,
    "travel at the speed of light is a good idea. ": 34,
    "I do not fully agree with you but that is OK. ": 34,
    "gas bills are sent out monthly or bimonthly. ": 36,
    "we things that earth quakes are predictable. ": 37,
    "life is but a dream so let us dream a lot. ": 31,
    "take it to the recycling depot tomorrow. ": 33,
    "sent this by registered mail with insurance. ": 37,
    "fall is my favorite season but spring is OK too. ": 38,
    "a fox is a very smart animal or so we think. ": 33,
    "the kids are excited about their vacation. ": 35,
    "this parking lot is full of trucks and vans. ": 35,
    "my bike has a flat tire so I will be late. ": 31,
    "do not walk too quickly or you might be early. ": 36,
    "when a duck goes quack it is asking for food. ": 35,
    "it has a limited warranty of only two years. ": 35,
    "the four seasons will come one after the other. ": 38,
    "the sun rises in the east and sets in the west. ": 36,
    "it is very windy today and it might rain too. ": 35,
    "do not worry about this because it is over. ": 34,
    "dashing through the snow is the best way to go. ": 37,
    "want to join us for lunch this afternoon. ": 33,
    "stay away from strangers is good advice. ": 33,
    "you must be accompanied by an adult. ": 29,
    "see you later alligator in a while crocodile. ": 37,
    "go ahead and make my day you sucker. ": 28,
    "I can play much better after my lesson. ": 31,
    "who cares if she wears a bit too much makeup. ": 35,
    "I feel my bare face in the wind and sun. ": 30,
    "Batman wears a cape and mask. ": 23,
    "I hate baking pies but I love to eat them. ": 32,
    "Lydia wants to go home right after the concert. ": 38,
    "I want to win first prize in the contest. ": 32,
    "Freud wrote of the ego and the id. ": 26,
    "I do not care if you do that but be careful. ": 33,
    "always cover all the bases just to be safe. ": 34,
    "nobody cares anymore about anything. ": 31,
    "can we play cards tonight or tomorrow. ": 31,
    "get rid of that immediately or else. ": 29,
    "I watched the movie blazing saddles. ": 30,
    "whole is greater than the sum of the parts. ": 34,
    "They love to yap about everything and nothing. ": 38,
    "when I peek out the window and watch for you. ": 35,
    "be home before midnight or you are in trouble. ": 37,
    "I think he played a pimp in that movie. ": 30,
    "I skimmed through your proposal this morning. ": 38,
    "he was wearing a sweatshirt with a hood. ": 32,
    "no more war no more bloodshed. ": 24,
    "toss the ball around the gymnasium. ": 29,
    "I will meet you at noon by the museum. ": 29,
    "I wanted to hold your hand at the party. ": 31,
    "the children are playing a game. ": 26,
    "Superman never wore a mask or a hat. ": 28,
    "this tape is so cool I listen to it everyday. ": 35,
    "he is shouting very loudly. ": 22,
    "you must correct your diction immediately. ": 36,
    "seasoned golfers love the game. ": 26,
    "he cooled off after she left the room. ": 30,
    "my dog sheds his hair on the sofa. ": 26,
    "you should join us on the patio. ": 25,
    "these cookies were so amazing I ate them all. ": 36,
    "I can still feel your presence. ": 25,
    "the dog will bite you if you tease it. ": 29,
    "the most ridiculous thing I have ever heard. ": 36,
    "where did you get such a wonderful tie. ": 31,
    "my what a lovely red jacket you are wearing. ": 35,
    "do you like to shop on Sunday. ": 23,
    "sorry but I spilled my coffee on the carpet. ": 35,
    "the Pacific is the largest of the five oceans. ": 37,
    "shall we play a round of five card stud. ": 31,
    "most Olympic athletes use banned substances. ": 38,
    "my mother makes the best ginger snap cookies. ": 37,
    "do a good deed to someone each and every day. ": 35,
    "quick there is someone knocking at the front door. ": 41,
    "flashing red light means stop and look both ways. ": 40,
    "sprawling subdivisions are bad for the environment. ": 44,
    "where on earth did I leave my glasses. ": 30,
    "try not to get lost on the way to the cottage. ": 35,
    "there is a lot of chlorine in the water today. ": 36,
    "do not drink the water unless you boil it first. ": 38,
    "the heater in my car always breaks in the winter. ": 39,
    "Santa Claus got stuck coming down the chimney. ": 38,
    "public transit is much faster than driving. ": 36,
    "zero in on the facts before doing anything. ": 35,
    "not much fun making up these stupid phrases. ": 36,
    "if I typed any faster my fingers would fall off. ": 38,
    "rain rain go away come again another day. ": 33,
    "pesticides are bad for the environment. ": 33,
    "universities are too expensive these days. ": 36,
    "the price of gas has gone through the roof. ": 34,
    "the winner of the race gets a gold medal. ": 32,
    "we drive on parkways and park in driveways. ": 35,
    "shall we go out for some pizza and beer. ": 31,
    "a coordinated effort is what it will take. ": 34,
    "where oh where can my little dog be. ": 28,
    "if you were not so stupid you would be smart. ": 35,
    "you are not quite so smart as you think. ": 31,
    "do you like to go camping in the rain. ": 29,
    "this person is a walking disaster. ": 28,
    "he captured the imagination of the nation. ": 35,
    "this is universally understood to be wrong. ": 36,
    "the stomach to listen to five hours of opera. ": 36,
    "an occasional taste of chocolate will not hurt you. ": 42,
    "the victims of crime deserve more redress. ": 35,
    "the protesters blocked all traffic on the road. ": 39,
    "the acceptance speech was really boring. ": 34,
    "if you work really hard you will reach the summit. ": 40,
    "a little encouragement is all it takes. ": 32,
    "there is a stiff penalty for staying out too late. ": 40,
    "is it true that the pen is mightier than the sword. ": 40,
    "exceed the maximum speed limit of the highway. ": 38,
    "your actions are in sharp contrast to your words. ": 40,
    "this leather jacket is too warm for springtime. ": 39,
    "the consequences of a wrong turn are severe. ": 36,
    "this mission statement is full of baloney. ": 35,
    "do not shout or you will loose your voice. ": 33,
    "we picked every apple from every tree. ": 31,
    "are you sure you want to become a lawyer. ": 32,
    "the fourth edition was better than the third. ": 37,
    "this system of taxation is most unfair. ": 32,
    "there are beautiful paintings in the art gallery. ": 41,
    "a yard is almost as long as a meter. ": 27,
    "is it true that we missed your birthday. ": 32,
    "this coalition government will never work. ": 36,
    "the destruction of the rain forest is a concern. ": 39,
    "I like to play tennis but not on grass. ": 30,
    "she is acutely aware of her good looks. ": 31,
    "so you want your cake and you want to eat it too. ": 37,
    "this machinery is too complicated to operate. ": 38,
    "a glance in the right direction is all it took. ": 37,
    "I just cannot figure out these instructions. ": 37,
    "make sure you strictly follow the guidelines. ": 38,
    "an airport is a very busy place to work. ": 31,
    "mystery of the lost lagoon may never be solved. ": 38,
    "is there any indication that the end is in sight. ": 39,
    "the chamber of commerce makes important decisions. ": 43,
    "this phenomenon will never occur again. ": 33,
    "obligations must be met before you can leave. ": 37,
    "the sticker is valid until the end of the year. ": 37,
    "all complaints must be filed in writing. ": 33,
    "tickets to the concert are very expensive. ": 35,
    "a picture is worth a thousand words. ": 29,
    "this camera takes very nice photographs. ": 34,
    "it looks like a shack but to me it is a palace. ": 35,
    "the dog buried the bone in the garden. ": 30,
    "the daring young man on the flying trapeze. ": 35,
    "this equation has too many variables. ": 31,
    "for express delivery this is very slow. ": 32,
    "I would put on my glasses if I could find them. ": 36,
    "he scored a touchdown in the last minute. ": 33,
    "the treasury department has run out of money. ": 37,
    "a satisfactory response to the question. ": 34,
    "well connected with people in high places. ": 35,
    "the bathroom is a great place to read a magazine. ": 39,
    "the generation gap always gets wider. ": 31,
    "this chemical spill took forever to clean up. ": 37,
    "prepare for the exam at least one month prior. ": 37,
    "an interesting observation that you have made. ": 39,
    "the bank transactions was not registered. ": 35,
    "your classroom etiquette needs some work. ": 35,
    "we better investigate these allegations. ": 35,
    "stability of the nation hinges on the election. ": 39,
    "our house needs a new electrical panel. ": 32,
    "our silver anniversary is just around the corner. ": 41,
    "the presidential suite is a very busy location. ": 39,
    "the punishment had better fit the crime. ": 33,
    "sharp cheese is good for sharp minds. ": 30,
    "the registration period ended last month. ": 35,
    "you have my sympathy for being so gullible. ": 35,
    "the objective of the exercise was to win. ": 33,
    "an historic meeting but nothing came of it. ": 35,
    "very reluctant to enter into a discussion. ": 35,
    "he is very good at addition and subtraction. ": 36,
    "he has six daughters and seven sons. ": 29,
    "that is a thoroughly disgusting thing to say. ": 37,
    "make sure you sign the withdrawal slip. ": 32,
    "the diplomatic relations are very strained. ": 37,
    "the minimum amount of time you will wait. ": 33,
    "that is a very traditional way to dress. ": 32,
    "representing the aspirations of a nation. ": 35,
    "medieval times were very hard indeed. ": 31,
    "a security force of eight thousand soldiers. ": 37,
    "there are winners and losers in every campaign. ": 39,
    "the voters have turfed him out of office. ": 33,
    "it takes forever to pay off a mortgage for a house. ": 40,
    "read about the collapse of the Roman empire. ": 36,
    "did you see that spectacular explosion last night. ": 42,
    "you must have receipts for all your expenses. ": 37,
    "the assault took six months to complete. ": 33,
    "very important to get your priorities in order. ": 39,
    "traveling to Mars requires a lot of fuel. ": 33,
    "the ship is longer than a football field. ": 33,
    "a good joke deserves a good laugh. ": 27,
    "the union will go on strike next Wednesday. ": 35,
    "religion and politics should never be mixed. ": 37,
    "complex interactions between men and women. ": 37,
    "where on earth did you get such a silly idea. ": 35,
    "it is cloudy today but it should be sunny tomorrow. ": 41,
    "a psychiatrist will help you if you feel depressed. ": 42,
    "if you are sick you should visit to a doctor. ": 35,
    "he is very busy so you must make an appointment. ": 38,
    "that fax machine seems to be malfunctioning. ": 37,
    "players of the game must know all the rules. ": 35,
    "a dog is supposed to be the best friend of a man. ": 37,
    "would you like to come over to my house to play. ": 37,
    "in a leap year February has an extra days. ": 33,
    "do not feel too bad just because you lost the race. ": 40,
    "this library sure has a lot of books in it. ": 33,
    "road construction makes traveling very difficult. ": 43,
    "he called seven times but the line was busy. ": 35,
    "that is a very odd question that you asked. ": 34,
    "left with a feeling of complete exasperation. ": 38,
    "in troubled times we must redouble our efforts. ": 39,
    "there is no kissing allowed in the library. ": 35,
    "that bilateral agreement is rife with problems. ": 40,
    "each constituent votes according to her conscience. ": 44,
    "my favourite sport is the demolition derby. ": 36,
    "that is truly shocking news and I am sad to hear it. ": 40,
    "the gun discharged when it was put down. ": 32,
    "that is one of the poorest nations on the planet. ": 39,
    "the algorithm is too complicated for me to understand. ": 45,
    "your presentation yesterday was very inspiring. ": 41,
    "that tract of land is owned by the government. ": 37,
    "burglars never leave behind their business card. ": 41,
    "the fire blazed for the entire weekend. ": 32,
    "if diplomacy does not work then a war might follow. ": 41,
    "please keep this completely confidential. ": 36,
    "the rationale behind the decision was sound. ": 37,
    "the cat had a very pleasant temperament. ": 33,
    "our housekeeper always does a very thorough job. ": 40,
    "her majesty visited our country this summer. ": 37,
    "handicapped persons need special consideration. ": 42,
    "these barracks are big enough for ten soldiers. ": 39,
    "he likes to sing the gospel and the blues. ": 33,
    "he underwent triple bypass surgery just last week. ": 42,
    "learning the ropes of a new organization. ": 34,
    "peering through a small hole that leads to nowhere. ": 42,
    "my lexicon is rapidly running short on words. ": 37,
    "it is difficult to concentrate with so much noise. ": 41,
    "give me one spoonful of Maxwell House coffee. ": 37,
    "as good as two or three cups of the other coffee. ": 38,
    "just like it says on the can good to the last drop. ": 39,
    "these two companies are about to announce a merger. ": 42,
    "electric cars need really big fuel cells. ": 34,
    "the plug does not fit the socket. ": 26,
    "drugs that are addicting should be avoided. ": 36,
    "the most beautiful sunset I have ever seen. ": 35,
    "it is fun to dine out on the weekends. ": 29,
    "get aboard because the ship is leaving. ": 32,
    "the water was monitored daily for impurities. ": 38,
    "he watched in astonishment as the game proceeded. ": 41,
    "a great big scratch on the tabletop. ": 29,
    "salesmen must make their monthly quota or else. ": 39,
    "saving that child was a truly heroic effort. ": 36,
    "granite is one of the hardest of all rocks. ": 34,
    "the offenders must be brought to justice. ": 34,
    "every Saturday he folds all the laundry. ": 33,
    "careless driving will result in a hefty fine. ": 37,
    "microscopes make small things look really big. ": 39,
    "here is a coupon for a free sample. ": 27,
    "cholesterol is fine but only in moderation. ": 36,
    "archaeology is a subject one can really dig. ": 36,
    "alliances are important for political parties. ": 40,
    "that sticker needs to be validated each month. ": 38,
    "the forest fire raged for an entire month. ": 34,
    "one can never take too many precautions. ": 33,
    "we have enough witnesses for a could case. ": 34,
    "labour unions really know how to organize. ": 35,
    "people blow their horn a lot around here. ": 33,
    "a correction had to be published right away. ": 36,
    "I like baroque music and classical music. ": 34,
    "the proprietor was unavailable for a meeting. ": 38,
    "important to be discreet about our meetings. ": 37,
    "can we meet tomorrow in the lavatory. ": 30,
    "the suburbs are sprawling over the countryside. ": 40,
    "shivering is one of the best ways to keep warm. ": 37,
    "dolphins swim fast and leap high out of the water. ": 40,
    "choose between maternity leave and paternity leave. ": 44,
    "the ventilation system seems to be broken. ": 35,
    "dinosaurs have been extinct for a long time. ": 36,
    "electricity is an inefficient way to heat a house. ": 41,
    "the bus was so crowded there were no empty seats. ": 39,
    "an injustice is committed pretty well every day. ": 40,
    "the coronation of the king was very exciting. ": 37,
    "I looked in the syllabus but it was not there. ": 36,
    "rectangular objects have four sides. ": 31,
    "prescription drugs require a note from a doctor. ": 40,
    "the insulation is not working very well. ": 33,
    "there is nothing finer than discovering a treasure. ": 43,
    "our life expectancy has increased substantially. ": 42,
    "an expression that the cream rises to the top. ": 37,
    "the high waves are threatening to swamp us. ": 35,
    "the treasurer must keep her hands out of the pot. ": 39,
    "completely sold out of that commodity. ": 32,
    "the general vicinity of the location of the crime. ": 41,
    "the installation of the chancellor was very boring. ": 43,
    "the scene of the accident is a shrine for fans. ": 37,
    "a tumor is OK as long as it is benign. ": 28,
    "would you please take a bath this month. ": 32,
    "usually rent is paid at the beginning of each month. ": 42,
    "for murder you will get a very long prison sentence. ": 42,
    "smokers have a much higher risk of getting cancer. ": 41,
    "you should probably quit while you are ahead. ": 37,
    "the knee bone is connected to the thigh bone. ": 36,
    "it is safe to walk the streets in the evening. ": 36,
    "my wallet was found but the money was missing. ": 37,
    "one hour is allotted as a question period. ": 34,
    "so you think you deserve a raise in your allowance. ": 41,
    "they watched the entire movie even the credits. ": 39,
    "good jobs for those with a university education. ": 40,
    "the fish were jumping right out of the water. ": 36,
    "the trains are always late around here. ": 32,
    "sit at the front of the bus if you want a good view. ": 39,
    "do you prefer a window seat or an aisle seat. ": 35,
    "the food at this restaurant really stinks. ": 35,
    "Canada has ten provinces and three territories. ": 40,
    "my gosh the elevator door appears to be stuck. ": 37,
    "raindrops keep falling on my head. ": 28,
    "spilling coffee on the carpet is bad news. ": 34,
    "telephones are an excellent way to communicate. ": 40,
    "with each step forward he takes two steps back. ": 38,
    "Superman is faster than a speeding bullet. ": 35,
    "wishful thinking is fine if you are an optimist. ": 39,
    "there is nothing wrong with my management style. ": 40,
    "arguing with the boss will get you nowhere. ": 35,
    "taking the train is usually faster than driving. ": 40,
    "what goes up most likely will come down. ": 32,
    "unions must be persistent to win a strike. ": 34,
    "presidents usually drive expensive cars. ": 35,
    "the stock exchange went on a nose dive. ": 31,
    "why do you ask such silly questions. ": 29,
    "that is a very nasty cut you have on your knee. ": 36,
    "what will we do when the oil wells run dry. ": 33,
    "you had better learn to walk before you try to run. ": 40,
    "having lots of insurance is important for bad drivers. ": 45,
    "traveling to conferences is a lot of fun. ": 33,
    "do you get nervous when you speak in public. ": 35,
    "pumping breaks helps if the roads are slippery. ": 39,
    "parking tickets can be challenged in court. ": 36,
    "apartments are too expensive in this neighbourhood. ": 44,
    "finding a nearby parking spot is a real challenge. ": 41,
    "gun powder must be handled with great care. ": 35,
    "a holiday on a beach is just what the doctor ordered. ": 42,
    "venom from a rattle snake is very poisonous. ": 36,
    "weeping willows are usually found near water. ": 38,
    "I cannot believe I ate the whole thing. ": 31,
    "that was the biggest hamburger I have ever seen. ": 39,
    "all gamblers will eventually loose their shirts. ": 41,
    "creative exercises are good for the mind. ": 34,
    "irregular verbs are the bane of all students. ": 37,
    "students of linguistics find your comment offensive. ": 45,
    "if you tell a lie your nose will begin to grow. ": 36,
    "an enlarged nose suggests you are a liar. ": 33,
    "that lie detector test will never work on me. ": 36,
    "if you lie in court you will be charged with contempt. ": 43,
    "most judges are very honest people. ": 29,
    "only an idiot would tell a lie in court. ": 31,
    "important news always seems to be late in arriving. ": 42,
    "please try to be home before midnight. ": 31,
    "if you come home too late the doors might be locked. ": 41,
    "the dormitory doors will be locked at midnight. ": 39,
    "staying up all night to study is a bad idea. ": 34,
    "is it true that you are a capitalist pig. ": 32,
    "those motivational seminars really make me sick. ": 41,
    "the wisdom of the courts should never be questioned. ": 43,
    "rejection letters are very discouraging. ": 35,
    "evidently that was the first time he tried to swim. ": 41,
    "that referendum asked a really silly question. ": 39,
    "there is a steep learning curve in riding a unicycle. ": 43,
    "a good stimulus deserves and even better response. ": 42,
    "everybody looses in most custody battles. ": 35,
    "putting our garbage in an abandoned mine is dumb. ": 40,
    "the recruitment of employees takes a lot of effort. ": 42,
    "gratifying experiences are hard to come by. ": 36,
    "everyone wants to win the lottery tonight. ": 35,
    "crossing the picket line gives me the chills. ": 37,
    "driving in the rain at night is very dangerous. ": 38,
    "leave now or you will surely be late. ": 29,
    "five more minutes is all that it takes. ": 31,
    "hurry home right after class or you will be late. ": 39,
    "never being late is very difficult to accomplish. ": 41,
    "it is very cold please turn up the heat. ": 31,
    "hot chocolate is good on a cold winter day. ": 34,
    "wear thermal underwear during the winter. ": 35,
    "have a really terrific summer holiday. ": 32,
    "can you show me the way to San Jose. ": 27,
    "did you borrow my pencil case or binder. ": 32,
    "the gauge indicates that my tank is empty. ": 34,
    "watch out for flying truck tires. ": 27,
    "mountain climbing is my favourite pastime. ": 36,
    "the hockey game had four periods of overtime. ": 37,
    "a goal was scored in the last second of the game. ": 38,
    "the goalie got a shutout in his very first game. ": 38,
    "figure skaters spend a lot of time on the ice. ": 36,
    "under most circumstances this is considered normal. ": 44,
    "a little too far fetched to be taken seriously. ": 38,
    "it was a very good joke for those who understood it. ": 41,
    "Thomas the Tank Engine just loves his trunk line. ": 40,
    "has anyone seen where I left my car keys. ": 32,
    "much practice is required to become a professional. ": 43,
    "air cadets and sea cadets have really cool uniforms. ": 43,
    "where is the best place to hide some cigarettes. ": 39,
    "wild horses are running down the valley. ": 33,
    "a stampede of steers is very hard to control. ": 36,
    "please do not be late for your music lesson. ": 35,
    "something tells me you are not very serious. ": 36,
    "mandatory jail sentences for all cases of fraud. ": 40,
    "her aspirations are very high indeed. ": 31,
    "incidentally what did you say your name was. ": 36,
    "most companies try very hard to avoid bankruptcy. ": 41,
    "reservations at this restaurant are not needed. ": 40,
    "important witnesses should be highly credible. ": 40,
    "honestly I just do not understand your point. ": 37,
    "dinosaurs existed long before we walked the earth. ": 42,
    "traffic on this motorway is very heavy today. ": 37,
    "vaguely speaking it sounds like a good idea. ": 36,
    "my company is a subsidiary of a large corporation. ": 41,
    "exploit the weaknesses of you enemy. ": 30,
    "construction is proceeding right on schedule. ": 39,
    "the bride and groom look very happy today. ": 34,
    "earthquakes are usually very predictable. ": 36,
    "this idea has a lot of momentum. ": 25,
    "comfortably positioned for a sweet victory. ": 37,
    "mercy killing is a hotly debated issue. ": 32,
    "the irony of the situation is beyond compare. ": 37,
    "keep doing the revisions until it is perfect. ": 37,
    "his jaw was broken and had to be sewn shut. ": 33,
    "aviators rarely travel in balloons these days. ": 39,
    "rolling hills and jagged rocks make good scenery. ": 41,
    "presently there are enough rations for everyone. ": 41,
    "vegetable gardens are a great place for leisure. ": 40,
    "stories of violence are absolutely appalling. ": 39,
    "protestations are rarely considered seriously. ": 41,
    "convey a clear message to get a point across. ": 36,
    "curiously that was the same idea as before. ": 35,
    "look to your parents for a glimpse to the future. ": 39,
    "home entertainment stores generally rent videos. ": 42,
    "various objects were on display in the window. ": 38,
    "likewise it was not entirely obvious. ": 31,
    "under what circumstances did this occur. ": 34,
    "the most likely answer it that it was raining. ": 37,
    "completely unexpected results sometimes occurs. ": 42,
    "rock and roll music is very loud and rhythmic. ": 37,
    "that drum solo was the greatest I ever heard. ": 36,
    "most toys are sold with batteries not included. ": 39,
    "pyramids are ancient tombs for pharaohs. ": 34,
    "hard breathing is often the results of exercise. ": 40,
    "this sentence fragment makes not sense to me. ": 37,
    "instrumental music was my favourite subject. ": 38,
    "this notorious criminal is eluding the police. ": 39,
    "an inquest will likely get to the bottom of this. ": 39,
    "it is under investigation so he cannot comment. ": 39,
    "dragged kicking and screaming across the street. ": 41,
    "the heart and lung association wants a donation. ": 40,
    "contributing money to charity is a worthy deed. ": 39,
    "proceeds will be used to offset the costs. ": 34,
    "guys and girls generally get along just fine. ": 37,
    "being upset about this is not a good idea. ": 33,
    "the electron rotates around the proton. ": 33,
    "molecules and atoms are the basis of all matter. ": 39,
    "his contemporaries thought he was just terrific. ": 41,
    "a lone duck must find some friends. ": 28,
    "proportional taxes do not sound fair to me. ": 35,
    "convert electrical energy to heat. ": 29,
    "intensively utilize all resources to their fullest. ": 44,
    "acknowledge all contributions buy your friends. ": 41,
    "mobile computers usually fit in a jacket pocket. ": 40,
    "the constable intervened in the disturbance. ": 38,
    "this conversation is going nowhere fast. ": 34,
    "breeding dogs is one way to make a living. ": 33,
    "state you thoughts succinctly and honestly. ": 37,
    "I need a hammer and screwdriver right away. ": 35,
    "the lecturer bored the class to sleep. ": 31,
    "archbishops give opinions only when they need to. ": 41,
    "copyright notices appear on each an every page. ": 39,
    "enjoyable experiences are remembered forever. ": 40,
    "a fragile object must be handled with care. ": 35,
    "improving literacy is the most important goal. ": 39,
    "accountants know how to operate calculators. ": 38,
    "a very slight disturbance in the force. ": 32,
    "fighter jets are good at nose dives. ": 29,
    "an interim solution seems like the only option. ": 39,
    "feminist viewpoints are to be respected. ": 34,
    "win the race to get a really nice trophy. ": 32,
    "chemical formulation for a new pain killer. ": 36,
    "continuously moving around the country. ": 34,
    "freight trains have box cars and gondola cars. ": 38,
    "magicians illusions are created with mirrors. ": 39,
    "metaphors can simplify learning and memory. ": 37,
    "what is the largest planet in the solar system. ": 38,
    "the closest planet to the sun is Mercury. ": 33,
    "hire a consultant if you need some good advice. ": 38,
    "an explosion frightened many of the children. ": 38,
    "attendance at the academy is mandatory. ": 33,
    "first impressions are not necessarily correct. ": 40,
    "he wandered aimlessly around the city. ": 32,
    "satisfying all ones needs is a tall order. ": 34,
    "jockey for position among the other contenders. ": 40,
    "be fruitful and multiply all numbers. ": 31,
    "education day is a good time to wear a suite. ": 35,
    "he shall not be greatly moved to agree with you. ": 38,
    "escape with the skin of your teeth. ": 28,
    "concession booths sell lots of junk food. ": 34,
    "civilization has advanced by leaps and bounds. ": 39,
    "deemed to be unnecessary and eliminated. ": 34,
    "prosperous times are the best to live in. ": 33,
    "trapped between a rock and a hard place. ": 32,
    "scared the living daylights out of him. ": 32,
    "spectators just keep coming and coming. ": 33,
    "more episodes are likely to be filmed. ": 31,
    "stepping stones make your trip much easier. ": 36,
    "stay away from volcanic eruptions if possible. ": 39,
    "the phone kept ringing off the hook. ": 29,
    "magazine subscription for a holiday gift. ": 35,
    "many think that man evolved from apes. ": 31,
    "the discovery of America was an accident. ": 34,
    "relying on a single source of information. ": 35,
    "freshly picked vegetables are full of vitamins. ": 40,
    "racist remarks have no place here. ": 28,
    "managers love to search for excellence. ": 33,
    "swimming in the ocean is a real challenge. ": 34,
    "delays will prevent us from arriving on time. ": 37,
    "be punctual or you will be late. ": 25,
    "goodbye to all the good people who attended. ": 36,
    "dismiss this idea as complete baloney. ": 32,
    "the magistrate bang the hammer on the table. ": 36,
    "grasp at straws if you have no further options. ": 38,
    "balanced approaches are usually preferred. ": 37,
    "this imposition cannot be tolerated. ": 31,
    "disco music gives me the jitters. ": 27,
    "dominate your opposition to win the game. ": 34,
    "internationally renowned journalist wins a prize. ": 43,
    "the prize fighter won the championship fight. ": 38,
    "hazards get in the way of a smooth voyage. ": 33,
    "the thief pulled a gun out of his pocket. ": 32,
    "unstable because of the constant noise. ": 33,
    "bones of contention must be addressed by all. ": 37,
    "arbitration seems the only path to a resolution. ": 40,
    "his bag of tricks seems to be empty. ": 28,
    "we Canadians just love to shovel show. ": 31,
    "is it true everyone wears snowshoes in Canada. ": 38,
    "around the earth in eighty days. ": 26,
    "backup but try not to hit the fire hydrant. ": 34,
    "everyone has a different opinion about this. ": 37,
    "the roof is leaking get a bucket. ": 26,
    "Christmas is coming and the goose is getting fat. ": 40,
    "centuries of erosion and little remains. ": 34,
    "kindly turn the volume down you are bothering me. ": 40,
    "dogs and cats generally do not get on well. ": 34,
    "the cat ate the mouse for breakfast. ": 29,
    "cheese is the preferred food for mice. ": 31,
    "rabbits enjoy a good feast of carrots. ": 31,
    "representatives of our nation are on vacation. ": 39,
    "specifically what is the point you wish to make. ": 39,
    "administrative duties are the bane of all professors. ": 45,
    "walk do not run when you cross the street. ": 33,
    "the spring offering of this course is cancelled. ": 40,
    "this course is easier if taken during the summer. ": 40,
    "the clock keeps on ticking and I keep on writing. ": 39,
    "do not go there it is too sensitive an issue. ": 35,
    "volume control on the amplifier goes up to eleven. ": 41,
    "sell off your assets if you need some extra cash. ": 39,
    "keen students always do extra homework. ": 33,
    "images of the Olympics inspire us all. ": 31,
    "victim statements bring many to tears. ": 32,
    "options for recovery are few and far between. ": 37,
    "the outcome of the exam was very pleasing. ": 34,
    "dead wood is found in a government ministry. ": 36,
    "gradually the air leaked from the tire. ": 32,
    "a pale blue smoke sifted up from the ruins. ": 34,
    "a remarkable outcome given the circumstances. ": 39,
    "vigorous exercise is good for stress management. ": 41,
    "yards of cloth were required for the dress. ": 35,
    "joint expansion caused the structure to fail. ": 38,
    "are you nervous about your upcoming interview. ": 39,
    "what is your favourite television show. ": 33,
    "billions of viewers watch soccer matches. ": 35,
    "the promise land bears no fruit. ": 26,
    "future promises lured immigrants to come. ": 35,
    "hot food produces gastric pain. ": 26,
    "the time for consultation is past. ": 28,
    "democracy and referenda go hand in had. ": 32,
    "dimpled ballots raised many questions. ": 33,
    "litigation is flourishing in America. ": 32,
    "never a borrower nor a lender be. ": 26,
    "the game is not over until it is over. ": 29,
    "do not miss your connecting flight. ": 29,
    "purple and green are popular colours. ": 31,
    "exact a high price for your services. ": 30,
    "this investigation is going nowhere. ": 31,
    "softeners are hard on washing machines. ": 33,
    "our backyard has a clothesline. ": 26,
    "snow is in the forecast for today. ": 27,
    "prepare a dossier before the meeting. ": 31,
    "job hunting necessitates having a resume. ": 35,
    "notices may not be posted here. ": 25,
    "roughly stated your assumption is correct. ": 36,
    "correct all errors before proceeding. ": 32,
    "broad assumptions invite criticism. ": 31,
    "classroom rules are hard to enforce. ": 30,
    "students sat in the aisles of the classroom. ": 36,
    "no hurry to walk down the aisle. ": 25,
    "technological advances appear everyday. ": 35,
    "no attendance without an invitation. ": 31,
    "message from the foreign correspondent. ": 34,
    "offhand your observation seems correct. ": 34,
    "approximating the result is fine. ": 28,
    "solution to the equation is imaginary. ": 32,
    "declare your assets to the bank. ": 26,
    "mix these chemicals to get an explosion. ": 33,
    "front door entrances are preferred by most. ": 36,
    "a double garage is absolutely essential. ": 34,
    "oil is leaking all over the driveway. ": 30,
    "politically sensitive issues are avoided. ": 36,
    "sensitive skin needs special cream. ": 30,
    "a classic book that was read by millions. ": 33,
    "classical music predates romantic music. ": 35,
    "art is inseparable from society. ": 27,
    "bringing out the best in people. ": 26,
    "skating on thin ice is dangerous. ": 27,
    "cycling without a helmet is prohibited. ": 33,
    "sleeping on park benches in not allowed. ": 33,
    "offhand comments may get you into trouble. ": 35,
    "good advice is to keep expectations low. ": 33,
    "lethal injection is a reasonable choice. ": 34,
    "rap music is preferred by many teenagers. ": 34,
    "putting on a happy face is sometimes difficult. ": 39,
    "save your pennies for the charity basket. ": 34,
    "teenagers really get under my skin. ": 29,
    "airport runways are accident prone. ": 30,
    "table top dancing is not a profession. ": 31,
    "rolling down the steep hill. ": 23,
    "because it just does not make any sense. ": 32,
    "but what difference does that make. ": 29,
    "extra time is needed to finish the project. ": 35,
    "when it rains the water will rise. ": 27,
    "shoreline is rapidly receding. ": 26,
    "water is becoming a scarce commodity. ": 31,
    "must have been something I said. ": 26,
    "waiting in line is a great pastime. ": 28,
    "plush sofas put people to sleep. ": 26,
    "aggravated assault is a serious crime. ": 32,
    "can you lend me fifty dollars please. ": 30,
    "read the newspaper cover to cover. ": 28,
    "time for another visit to the dentist. ": 31,
    "of course it did quite happen like that. ": 32,
    "anniversaries should not be forgotten. ": 33,
    "ten weeks on the best selling list. ": 28,
    "never have a drink before ten in the morning. ": 36,
    "almost missed the bus this morning. ": 29,
    "sounds like you had a terrible time. ": 29,
    "brush your teeth after every meal. ": 28,
    "so hungry I could eat a horse. ": 23,
    "pigeons enjoy a stroll in the park. ": 28,
    "time to turn off my computer. ": 23,
    "batteries need to be recharges often. ": 31,
    "glue the cuttings onto the project board. ": 34,
    "water the plants at least twice a week. ": 31,
    "escalators are quicker than stairs. ": 30,
    "luxury condominium is an oxymoron. ": 29,
    "crossword puzzles take a lot of time. ": 30,
    "an expert at chess and scrabble. ": 26,
    "will this project finish on schedule. ": 31,
    "children shows should be educational. ": 32,
    "water buffalo used to roam here. ": 26,
    "the railway goes from coast to coast. ": 30,
    "after the storm the sun shined brightly. ": 33,
    "try not to make too many mistakes. ": 27,
    "this is the last reminder you will get. ": 31,
    "many children are playing in the park. ": 31,
    "my car needs a new muffler and new brakes. ": 33,
    "it is getting very crowded in this airport. ": 35,
    "many people are standing around doing nothing. ": 39,
    "I have had enough thank you very much. ": 30,
    "did you see that plane fly by. ": 23,
    "this weather is really getting me down. ": 32,
    "when will the sun break through the clouds. ": 35,
    "we are rapidly running out of time. ": 28,
    "please declare your position on this issue. ": 36,
    "traveling to a foreign country may require a visa. ": 41,
    "my passport expires in three years. ": 29,
    "nobody every warned me about that. ": 28,
    "it seemed completely natural at the time. ": 34,
    "my exercise plan will begin next year. ": 31,
    "contracts must be tightly worded. ": 28,
    "the line was busy so I will call back later. ": 34,
    "blank tapes are needed to record movies. ": 33,
    "dim the lights to create some atmosphere. ": 34,
    "the lecturer wore a lapel microphone. ": 31,
    "a coffee goes good after a business luncheon. ": 37,
    "overtime rates apply on Saturday and Sunday. ": 37,
    "wait for traffic to stop before crossing. ": 34,
    "open the window to get a nice breeze. ": 29,
    "the elevator was stuck between floors. ": 32,
    "the tallest hotel building in the city. ": 32,
    "subways usually travel under ground. ": 31,
    "purchase a ticket just to be sure. ": 27,
    "are you visiting this weekend or next. ": 31,
    "fall chores include raking leaves. ": 29,
    "it is a sunny day so wear a hat. ": 23,
    "late due to the construction. ": 24,
    "customer satisfaction is our top priority. ": 36,
    "it really does not matter one way or the other. ": 37,
    "countertops need to be cleaned regularly. ": 35,
    "washing dishes is not very much fun. ": 29,
    "promises to reduce the national debt. ": 31,
    "go to war and come home in a box. ": 24,
    "first class mail will take just two days. ": 33,
    "is it true that storks deliver babies. ": 31,
    "the cat ate the mouse and the dog ate the cat. ": 35,
    "verify that you deposited the cheque correctly. ": 40,
    "it seems to be the only solution to the problem. ": 38,
    "unlikely to cause a major disturbance. ": 32,
    "the laundry was hung out to dry. ": 25,
    "have pity on me officer I was late for work. ": 34,
    "when did you say your birthday was. ": 28,
    "do not through stones at passers by. ": 29,
    "conspiracy is punishable by death. ": 29,
    "the are many limitations to this approach. ": 35,
    "bowl of cereal or two pieces of toast. ": 30,
    "lifetime memberships are revoked immediately. ": 40,
    "productivity has improved tremendously. ": 35,
    "reflects the changing shape of the landscape. ": 38,
    "tourist resort is crowded in the summertime. ": 37,
    "greatly influenced by ones elders. ": 29,
    "the magnitude of the error is one hundred percent. ": 41,
    "this outbreak of measles could have been prevented. ": 43,
    "cave dwellers live near the base of mountains. ": 38,
    "caring workers are needed immediately. ": 33,
    "the chorus of cheers was resounding. ": 30,
    "tensions are rising on each side of the border. ": 38,
    "the ambassador was caught with his pants down. ": 38,
    "reluctantly we walked down the aisle. ": 31,
    "a compromise solution to the dilemma. ": 31,
    "torn between loyalty and love. ": 25,
    "rebel invasion must be stopped at all cost. ": 35,
    "indigenous people own the rights to the land. ": 37,
    "meaningful only in the context of the situation. ": 40,
    "made a fortune selling vegetables in the market. ": 40,
    "your demands are quite unreasonable. ": 31,
    "a penny or two here and there will not be missed. ": 38,
    "the overwhelming majority voted yes. ": 31,
    "struggled to get to the finish line. ": 29,
    "accounting practices are most unorthodox. ": 36,
    "admiration comes with competence. ": 29,
    "a very ambitious project to undertake. ": 32,
    "waste management is important in the city. ": 35,
    "remove the sign from the wall immediately. ": 35,
    "this dispute may never be resolved. ": 29,
    "lunchtime is just an hour away. ": 25,
    "light bulbs rarely need to be replaced. ": 32,
    "place a napkin on your lap before you eat. ": 33,
    "cell regeneration is a very slow process. ": 34,
    "oil paints are the hardest to apply. ": 29,
    "three dimes two nickels and a penny. ": 29,
    "will this key open the back door. ": 26,
    "my fountain pen has run out of ink. ": 27,
    "fire engines have loud sirens. ": 25,
    "swimming across the lake is a real challenge. ": 37,
    "massage therapy will not fix your sore back. ": 36,
    "software bugs drive most users crazy. ": 31,
    "the switch on the wall operates the stereo. ": 35,
    "her travel agent is busy this week. ": 28,
    "free prize in every box of cereal. ": 27,
    "business card collection is expanding. ": 33,
    "planetary travel must wait a few more years. ": 36,
    "what kind of cheese is found on the moon. ": 32,
    "water bottle filled with a thirst quencher. ": 36,
    "television actors make a lot of money. ": 31,
    "signing autographs is very boring. ": 29,
    "seven dollars plus a lot of change. ": 28,
    "people are dieing to get into the cemetery. ": 35,
    "taxi rides are generally quite bumpy. ": 31,
    "do not tip when you are in Europe. ": 26,
    "vessels travel across the ocean slowly. ": 33,
    "rockets were fired into enemy territory. ": 34,
    "gas furnaces generate a lot of heat. ": 29,
    "fuel efficiency is a desirable feature. ": 33,
    "do not hold your breath for electric cars. ": 34,
    "three more nights in a hotel room. ": 27,
    "free breakfast is offered with every room. ": 35,
    "unfortunately the food will rot your stomach. ": 38,
    "ask for more than what you really need. ": 31,
    "big pockets can hold large items. ": 27,
    "the warmest December in twenty years. ": 31,
    "usually there is a lot of snow by now. ": 29,
    "shirts and shoes must be worn here. ": 28,
    "overcoats are necessary in January. ": 30,
    "red carpets and green walls look awful. ": 32,
    "leave the window open for a cool breeze. ": 32,
    "an elevator is sometimes called a lift. ": 32,
    "coffee is essential first thing in the morning. ": 39,
    "are you a coffee drinker or a tea drinker. ": 33,
    "use a napkin in case you spill some. ": 28,
    "shall we walk or take the elevator. ": 28,
    "take the elevator up but take the stairs down. ": 37,
    "can those containers be recycled. ": 28,
    "my watch gains a minute or two each day. ": 31,
    "enough pocket change to buy a cup of coffee. ": 35,
    "spell checkers flag correct words as wrong. ": 36,
    "foreigners should register with their embassy. ": 40,
    "use a stop watch to time the race. ": 26,
    "the winner by one hundredth of a second. ": 32,
    "free coffee in the lobby for all guests. ": 32,
    "a taxi is faster than public transit. ": 30,
    "cable modems are the fastest way to connect. ": 36,
    "a major snowstorm is forecast for tomorrow. ": 36,
    "my telephone cord is all twisted. ": 27,
    "lazy chair with head rest and foot rest. ": 32,
    "circular staircase with oak handrail. ": 32,
    "coming out of retirement to win the championship. ": 41,
    "extension cord with eight receptacles. ": 33,
    "more than half the flights were canceled. ": 34,
    "keep all your receipts and save them in a shoebox. ": 40,
    "food and entertainment are reimbursed as expenses. ": 43,
    "is the glass half full or half empty. ": 29,
    "playground equipment is sometimes dangerous. ": 39,
    "subscriptions expires at the end of the year. ": 37,
    "the editorial page is read thoroughly. ": 32,
    "old magazines are found in the waiting room. ": 36,
    "give discarded clothes to the poor and needy. ": 37,
    "elastic bands holds things together. ": 31,
    "water skiing requires a helmet and life vest. ": 37,
    "cross country skiing builds strong arm muscles. ": 40,
    "Rocky went the distance with the champ. ": 32,
    "pets as presents are often returned later. ": 35,
    "the key on the bottom is for the space character. ": 39,
    "your suggestion seems quite ambiguous. ": 33,
    "time to put prejudices aside and become neighbours. ": 43,
    "Sumo wrestlers need to rest a lot. ": 27,
    "a group singing carols at the front door. ": 33,
    "decorate the house with red and green lights. ": 37,
    "leave milk and cookies for Santa Claus. ": 32,
    "how many reindeer put his sleigh. ": 27,
    "holiday music puts everyone in a good mood. ": 35,
    "sales are very brisk during the holiday season. ": 39,
    "the seconds just keep ticking away. ": 29,
    "a pancake house on every corner. ": 26,
    "an extended forum for small groups to meet. ": 35,
    "register early and you will get a discount. ": 35,
    "include payment along with your application. ": 38,
    "diverse members of the global community. ": 34,
    "courses cover a wider range of topics. ": 31,
    "a group of experienced doctors will attend. ": 36,
    "designed to provide diversity and depth. ": 34,
    "continuing education for professionals and adults. ": 44,
    "a small administration fee will be charged. ": 36,
    "participate fully in the learning activities. ": 39,
    "may result in the immediate termination. ": 34,
    "the right to prohibit conduct that is harmful. ": 38,
    "absence makes the heart grow fonder. ": 30,
    "the love of money is the root of all evil. ": 32,
    "love is never having to say you are sorry. ": 33,
    "a family that prays together stays together. ": 37,
    "the way to his heart is through his stomach. ": 35,
    "better to remain silent and be thought a fool. ": 37,
    "the road to hell is paved with good intentions. ": 38,
    "should we take the high road or the low road. ": 35,
    "a camel is a horse designed by committee. ": 33,
    "pull yourself up by your bootstraps. ": 30,
    "would you mind speaking a little more slowly. ": 37,
    "important to build brand awareness. ": 30,
    "nearly half of the people signed up. ": 29,
    "companies are just starting to catch on. ": 33,
    "a real problem in achieving any progress. ": 34,
    "the plants employ people at very low wages. ": 35,
    "approach technology with cautious judgment. ": 38,
    "environment issues are here to stay. ": 30,
    "fit into a larger corporate strategy. ": 31,
    "reasonably priced credit is readily available. ": 40,
    "a rise in interest rates is inevitable. ": 32,
    "contrary to your attempt to raise alarm. ": 33,
    "no more opportunities to cast blame. ": 30,
    "a lot of people are fretting about that. ": 32,
    "an intense debate about whether to get tough. ": 37,
    "need for drastic measures to control inflation. ": 40,
    "wage pressures due to a shortage of workers. ": 36,
    "optimists say that will not happen for a while. ": 38,
    "many options his crew will have to consider. ": 36,
    "different individuals have different strengths. ": 42,
    "mutual respect and cooperation. ": 27,
    "its value to society is dubious. ": 26,
}