export const minimumNumberOfKeystrokes = {
"Mit ur faldt i vandet.": 23,
"Fremherskende vind fra øst.": 30,
"Aldrig for rig og aldrig for tynd.": 39,
"Det er svært at trække vejret.": 34,
"Jeg kan se ringene på Saturn.": 33,
"Fysik og kemi er svære.": 27,
"Min bankkonto er overtrukket.": 34,
"Valg frembringer det bedste.": 32,
"Vi får spaghetti.": 19,
"Tid til at handle ind.": 27,
"Et problem med motoren.": 27,
"Elefanter er bange for mus.": 31,
"Mit yndlingssted at besøge.": 32,
"Tre to en nul affyring.": 27,
"Mit yndlingsfag er psykologi.": 33,
"Forholdene er uacceptable.": 30,
"Pas på lavtflyvende genstande.": 36,
"Hvis du først ikke har succes.": 34,
"Angiv venligst din fødselsdato.": 37,
"Vi løber risikoen for at fejle.": 34,
"Bøn i skolen støder nogle.": 29,
"Han er ligesom alle andre.": 30,
"Stor forstyrrelse i kraften.": 33,
"Kærlighed betyder mange ting.": 32,
"Du må være ved at blive gammel.": 36,
"Verden er en scene.": 23,
"Må jeg stå på skøjter med søster i dag.": 43,
"Værken låner eller udlåner.": 30,
"Et pokkers spørgsmål.": 25,
"Et spørgsmål der må besvares.": 31,
"Pas på ides of March.": 26,
"Double double slid og besvær.": 31,
"Benægtelsens kraft.": 23,
"Jeg er enig med dig.": 25,
"Sig ikke noget.": 21,
"Spil den igen Sam.": 23,
"Kraften er med dig.": 25,
"Du er endnu ikke en jedi.": 31,
"Et tilbud du ikke kan afslå.": 33,
"Taler du til mig.": 23,
"Ja du er meget klog.": 25,
"Alt arbejde og ingen leg.": 31,
"Hårgele er meget fedtet.": 28,
"Valium i økonomistørrelse.": 32,
"Fakta står i vejen.": 25,
"Drømmernes drømmere.": 25,
"Havde du en god tid.": 25,
"Rummet er en høj prioritet.": 33,
"Du er et vidunderligt eksempel.": 36,
"Spild ikke din tid.": 25,
"Drik ikke for meget.": 26,
"Tag en kaffepause.": 25,
"Popularitet ønskes af alle.": 32,
"Musikken er bedre end den lyder.": 36,
"Stjernelys og dugdråbe.": 27,
"Livet er let.": 18,
"Fiskene springer.": 22,
"Bomulden er høj.": 22,
"Kørte min Chevy til dæmningen.": 34,
"Men dæmningen var tør.": 26,
"Jeg hentede roveren fra værkstedet.": 39,
"Film om en skør professor.": 28,
"Kom og se vores nye bil.": 30,
"Finder på skarpe sound bites.": 31,
"Jeg skal til musiktime.": 26,
"Modstanderholdet er derovre.": 32,
"Snart vender vi hjem fra byen.": 33,
"Jeg har slips og jakke på.": 27,
"Den hurtige brune ræv sprang.": 33,
"Alt sammen i en stor bunke.": 31,
"Bær en krone med mange juveler.": 35,
"Der kommer tåge i aften.": 29,
"Jeg er allergisk overfor bier og peanuts.": 44,
"Han er stadig på vores hold.": 31,
"Dow Jones-indekset er steget.": 32,
"Min foretrukne snack er chokolade.": 37,
"Kongen sender dig i tårnet.": 30,
"Vi er undersåtter og må adlyde.": 34,
"Mor strikkede hende en rullekrave.": 38,
"Guldlok og de tre bjørne.": 28,
"Vi handlede dagligvarer.": 27,
"Opgaven skal afleveres i dag.": 31,
"Hvad du ser er hvad du får.": 31,
"Kun til din orientering.": 25,
"En fjerdedel af et århundrede.": 33,
"Butikken lukker klokken ti.": 28,
"Hoved skulder knæ og tæer.": 28,
"Vaniljeis.": 11,
"Ofte stillede spørgsmål.": 27,
"Round robin-planlægning.": 29,
"Informationsmotorvejen.": 27,
"Min yndlingsbrowser.": 22,
"Laserprinteren er gået i stå.": 32,
"Alle gode drenge fortjener fudge.": 36,
"Det næststørste land.": 26,
"Ring for flere detaljer.": 28,
"Lige i tid til festen.": 27,
"Hav en god weekend.": 23,
"Videokamera med zoomlinse.": 29,
"Hvad en abe ser, gør en abe.": 34,
"Det er meget uheldigt.": 27,
"Baghaven til vores hus.": 27,
"Det er en meget god idé.": 30,
"Læseuge er lige på trapperne.": 36,
"Vores faxnummer er ændret.": 30,
"Tak for din hjælp.": 23,
"Ingen bytte uden bon.": 25,
"Den tidlige fugl får ormen.": 31,
"Spænd selen for sikkerheden.": 32,
"Det er for meget at håndtere.": 34,
"Beskyt dit miljø.": 24,
"Verdens befolkning vokser.": 29,
"Biblioteket er lukket i dag.": 30,
"Mary havde et lille lam.": 27,
"Undervisningstjenester vil hjælpe.": 36,
"Vi accepterer personlige checks.": 33,
"Dette er en nonprofitorganisation.": 38,
"Brugervenlig grænseflade.": 27,
"Sund mad er godt for dig.": 31,
"Praktisk erfaring med et job.": 33,
"Dette ur er for dyrt.": 26,
"Postvæsenet er meget langsomt.": 34,
"Kommunikér via e-mail.": 28,
"Hovedstaden i vores nation.": 30,
"Rejs med lysets hastighed.": 31,
"Jeg er ikke helt enig med dig.": 36,
"Gasregninger sendes månedligt.": 33,
"Jordskælv er forudsigelige.": 31,
"Livet er kun en drøm.": 27,
"Tag det til genbrugspladsen.": 32,
"Send dette som anbefalet post.": 34,
"Efterår er min yndlingsårstid.": 34,
"En ræv er et meget klogt dyr.": 33,
"Børnene er meget spændte.": 31,
"Parkeringspladsen er fuld af lastbiler.": 44,
"Min cykel har en punktering.": 33,
"Gå ikke for hurtigt.": 25,
"En and kvækker for mad.": 28,
"Begrænset garanti på to år.": 31,
"De fire årstider vil komme.": 33,
"Solen står op i øst.": 26,
"Det er meget blæsende i dag.": 32,
"Vær ikke bekymret for dette.": 34,
"Fart over feltet i sneen.": 30,
"Vil du med os til frokost.": 31,
"Hold dig væk fra fremmede.": 32,
"I selskab med en voksen.": 30,
"Vi ses senere alligator.": 29,
"Gør min dag, din nar.": 27,
"Jeg kan spille meget bedre nu.": 35,
"Hun bruger for meget makeup.": 31,
"Mit bare ansigt i vinden.": 30,
"Batman bærer en kappe.": 27,
"Jeg hader at bage tærter.": 30,
"Lydia vil gerne hjem.": 26,
"Vind førstepræmien i konkurrencen.": 38,
"Freud skrev om jeget.": 27,
"Jeg er ligeglad om du gør det.": 37,
"Dæk altid alle baser.": 28,
"Nu er der ingen, der bekymrer sig længere.": 44,
"Kan vi spille kort i aften.": 31,
"Fjern det straks.": 24,
"Jeg så Blazing Saddles.": 28,
"Summen af delene.": 22,
"De elsker at snakke om ingenting.": 38,
"Kig ud af vinduet.": 27,
"Vær hjemme før midnat.": 29,
"Han spillede en alfons i den film.": 38,
"Jeg skummede igennem dit forslag.": 37,
"Han havde en sweatshirt på.": 30,
"Ingen flere krige, ingen mere blodsudgydelse.": 47,
"Kast bolden rundt.": 26,
"Jeg møder dig klokken tolv.": 29,
"Jeg vil holde din hånd.": 28,
"Børnene leger.": 20,
"Superman bar aldrig maske.": 31,
"Jeg lytter til båndet hver dag.": 33,
"Han råber højt.": 21,
"Ret din diktion straks.": 27,
"Erfarne golfspillere elsker spillet.": 36,
"Han kølede af efter hun gik.": 31,
"Min hund fælder sit hår.": 28,
"Kom med på terrassen.": 27,
"Disse småkager er så fantastiske.": 38,
"Jeg kan stadig mærke din tilstedeværelse.": 42,
"Hunden vil bide dig.": 26,
"En helt latterlig ting.": 27,
"Hvor fik du det slips fra.": 30,
"Sikke en dejlig rød jakke.": 32,
"Kan du lide at shoppe om søndagen.": 38,
"Jeg spildte kaffe på tæppet.": 31,
"Det største af de fem oceaner.": 34,
"Skal vi spille en runde kort.": 33,
"Olympiske atleter bruger doping.": 35,
"Min mor laver gode småkager.": 32,
"Gør en god gerning for nogen.": 34,
"Skynd dig, der banker nogen på.": 36,
"Blinkende rødt lys betyder stop.": 35,
"Spredte villakvarterer er dårlige.": 36,
"Hvor lagde jeg mine briller.": 30,
"På vej til sommerhuset.": 26,
"Masser af klor i vandet.": 31,
"Drik ikke vandet.": 24,
"Min bil går altid i stykker om vinteren.": 42,
"Julemanden satte sig fast.": 30,
"Offentlig transport er meget hurtigere.": 38,
"Fokuser på fakta.": 24,
"Lav nogle flere sætninger.": 33,
"Mine fingre er meget kolde.": 31,
"Regn, regn, gå væk.": 26,
"Skadeligt for miljøet.": 27,
"Universiteter er for dyre.": 30,
"Benzinprisen er høj.": 27,
"Vinder af løbet.": 21,
"Vi kører på motorveje.": 27,
"Vi parkerer i indkørsler.": 28,
"Gå ud og få noget pizza og øl.": 38,
"Det kræver indsats.": 26,
"Hvor kan min lille hund være.": 33,
"Hvis du ikke var så dum.": 28,
"Ikke helt så smart som du tror.": 37,
"Kan du lide at campere.": 30,
"Den person er en katastrofe.": 32,
"Nationens fantasi.": 23,
"Universelt forstået som forkert.": 36,
"Lyt til fem timer opera.": 28,
"En lejlighedsvis smag af chokolade.": 39,
"Ofrene fortjener mere erstatning.": 37,
"Protestanterne blokerede al trafik.": 36,
"Accepteret tale var kedelig.": 33,
"Arbejd hårdt for at nå toppen.": 35,
"Der skal lidt opmuntring til.": 33,
"Hård straf for at være ude sent.": 35,
"Pen er mægtigere end sværdet.": 34,
"Overskrid maksimal hastighedsgrænse.": 39,
"I skarp kontrast til dine ord.": 34,
"Denne læderjakke er for varm.": 35,
"Konsekvenser af en forkert drejning.": 37,
"Denne missionserklæring er vrøvl.": 35,
"Du vil miste din stemme.": 32,
"Hvert æble fra hvert træ.": 28,
"Er du sikker på, at du vil have dette.": 41,
"Den fjerde udgave var bedre.": 33,
"Dette system af beskatning.": 33,
"Smukke malerier i galleriet.": 34,
"En yard er næsten en meter.": 32,
"Vi glemte din fødselsdag.": 31,
"Koalitionsregeringer virker aldrig.": 36,
"Ødelæggelse af regnskoven.": 29,
"Jeg kan lide at spille tennis.": 33,
"Meget bevidst om hendes skønhed.": 36,
"Du vil spise din kage.": 29,
"Maskineriet er for kompliceret.": 35,
"Et blik i den rigtige retning.": 35,
"Jeg kan bare ikke finde ud af det.": 39,
"Følg venligst retningslinjerne.": 33,
"En lufthavn er et meget travlt sted.": 38,
"Mysteriet om den tabte lagune.": 34,
"Er der nogen indikation af dette.": 35,
"Kammeret træffer vigtige beslutninger.": 38,
"Dette fænomen vil aldrig forekomme.": 39,
"Forpligtelser skal mødes først.": 36,
"Gyldig til udgangen af året.": 33,
"Indsend alle klager skriftligt.": 36,
"Billeter er meget dyre.": 30,
"Et billede siger mere end tusind ord.": 41,
"Denne kamera tager flotte fotografier.": 39,
"Det ligner en hytte.": 26,
"Hunden begravede benet.": 28,
"Den dristige unge mand.": 27,
"Denne ligning er for kompliceret.": 37,
"Ekspreslevering er meget hurtig.": 34,
"Jeg tager mine briller på.": 28,
"En touchdown i sidste minut.": 32,
"Finansministeriet er gået fallit.": 36,
"Et godt svar på spørgsmålet.": 33,
"Godt forbundet med mennesker.": 31,
"Badeværelset er godt til at læse.": 36,
"Generationskløften bliver større.": 36,
"Kemikaliespild tog evigheder.": 33,
"Forbered dig til eksamen på forhånd.": 39,
"Interessant observation blev gjort.": 35,
"Banktransaktionen blev ikke registreret.": 41,
"Din etikette skal arbejdes på.": 35,
"Vi bør undersøge dette.": 30,
"Stabilitet i nationen.": 25,
"Hus med nyt el-panel.": 28,
"Vores sølvbryllup nærmer sig.": 34,
"Præsident-suiten er meget travl.": 36,
"Straffen bør stå mål med forbrydelsen.": 45,
"Skarp ost holder sindet skarpt.": 36,
"Tilmeldingsperioden er slut.": 33,
"Du har min medfølelse.": 29,
"Målet med øvelsen.": 25,
"Historisk møde uden resultat.": 33,
"Meget tilbageholdende med at gå ind.": 41,
"Dygtig til addition og subtraktion.": 36,
"Seks døtre og syv sønner.": 27,
"En grundigt ulækker ting at sige.": 39,
"Underskriv udbetalingssedlen.": 33,
"Forholdene er meget anstrengte.": 35,
"Minimumstid.": 11,
"En meget traditionel måde at klæde sig på.": 45,
"Nationens aspirationer.": 27,
"Middelalderen var meget hård.": 32,
"En sikkerhedsstyrke på otte tusinde.": 40,
"Der er vindere og tabere.": 31,
"Vælgerne smed ham ud.": 29,
"Betal et realkreditlån for et hus.": 38,
"Romerrigets sammenbrud.": 29,
"Så du det spektakulære eksplosion.": 40,
"Gem kvitteringer for alle dine udgifter.": 41,
"Overfaldet tog seks måneder.": 34,
"Få dine prioriteter på plads.": 34,
"Rejser kræver meget brændstof.": 36,
"Længere end en fodboldbane.": 30,
"En god joke fortjener en god latter.": 42,
"Fagforeningen vil strejke.": 30,
"Bland aldrig religion og politik.": 36,
"Interaktioner mellem mænd og kvinder.": 39,
"Hvor fik du en sådan tåbelig idé fra.": 41,
"Det skulle være solrigt i morgen.": 36,
"En psykiater vil hjælpe dig.": 31,
"Du bør besøge en læge.": 29,
"Du skal bestille tid.": 27,
"Faxmaskinen er i stykker.": 31,
"Spillere skal kende alle regler.": 36,
"En hund er menneskets bedste ven.": 37,
"Vil du komme til mit hus.": 30,
"Februar har en ekstra dag.": 31,
"Tag det ikke for tungt.": 27,
"Dette bibliotek har mange bøger.": 36,
"Byggearbejde gør det svært at rejse.": 38,
"Han ringede syv gange.": 27,
"Det er et meget mærkeligt spørgsmål.": 39,
"En følelse af fuldstændig irritation.": 38,
"Vi må fordoble vores indsats.": 34,
"Ingen kys i biblioteket.": 28,
"Den aftale er fyldt med problemer.": 39,
"Stem efter din samvittighed.": 33,
"Min yndlingssport er racketball.": 36,
"Trist at høre den nyhed.": 31,
"Pistolen affyrede ved et uheld.": 36,
"En af de fattigste nationer.": 32,
"Algoritmen er for kompliceret.": 33,
"Din præsentation var inspirerende.": 36,
"Den jord tilhører regeringen.": 32,
"Indbrudstyve efterlader aldrig visitkort.": 42,
"Brandene rasede hele weekenden.": 36,
"Hvis diplomati ikke virker.": 27,
"Venligst hold dette fortroligt.": 33,
"Rationale bag beslutningen.": 27,
"Katten har et behageligt temperament.": 36,
"Vores husholderske gør et grundigt arbejde.": 44,
"Hendes majestæt besøgte vores land.": 37,
"Handicappede personer kræver hensyn.": 38,
"Disse kaserner er store nok.": 31,
"Syng gospel og blues.": 27,
"Han gennemgik triple bypass operation.": 39,
"De grundlæggende principper i en ny organisation.": 49,
"Kigger gennem et lille hul.": 31,
"Løber hurtigt tør for ord.": 30,
"Det er svært at koncentrere sig.": 34,
"Giv mig en skefuld kaffe.": 29,
"To eller tre kopper kaffe.": 27,
"Lige som der står på dåsen, god.": 38,
"Virksomheder annoncerer en fusion.": 35,
"Elektriske biler kræver store brændselsceller.": 46,
"Stikket passer ikke i kontakten.": 36,
"Stoffer bør undgås.": 24,
"Den smukkeste solnedgang.": 30,
"Vi spiser ude i weekenden.": 31,
"Kom om bord, skibet sejler.": 33,
"Vandet blev overvåget dagligt.": 33,
"Han så til sin forbløffelse.": 32,
"En stor ridse på bordpladen.": 33,
"Sælgere skal opfylde deres månedlige kvote.": 45,
"At redde barnet var en heroisk indsats.": 45,
"Granitten er den hårdeste af alle sten.": 41,
"Bring gerningsmændene for retten.": 36,
"Hver lørdag folder han vasketøjet.": 36,
"Uagtsom kørsel resulterer i bøde.": 38,
"Mikroskoper får små ting til at se store ud.": 48,
"Kupon til en gratis prøve.": 30,
"Fint, men kun med måde.": 28,
"Et fag man virkelig kan nyde.": 33,
"Vigtigt for politiske partier.": 32,
"Den sticker skal valideres.": 31,
"Brandene rasede i en hel måned.": 36,
"Man tager aldrig for mange forholdsregler.": 42,
"Vi har nok vidner.": 26,
"Fagforeninger ved, hvordan man organiserer.": 44,
"Folk bruger deres horn meget.": 33,
"En rettelse måtte offentliggøres.": 35,
"Jeg kan lide barok og klassisk musik.": 38,
"Ejeren var ikke tilgængelig.": 32,
"Vær diskret om dit møde.": 29,
"Mød i morgen på toilettet.": 31,
"Forstæder breder sig overalt.": 34,
"At ryste hjælper med at holde varmen.": 41,
"Delfiner springer højt ud af vandet.": 38,
"Prøv at nyde din barsel.": 33,
"Ventilationssystemet er i stykker.": 36,
"Dinosaurer har været uddøde i evigheder.": 42,
"En ineffektiv måde at opvarme et hus.": 39,
"Bussen var meget overfyldt.": 33,
"En uretfærdighed sker hver dag.": 36,
"Kroningen var meget spændende.": 34,
"Se i pensum for kurset.": 30,
"Rektangulære objekter har fire sider.": 38,
"Receptpligtig medicin kræver en seddel.": 42,
"Isoleringen virker ikke.": 27,
"Intet bedre end at finde en skat.": 38,
"Vores forventede levetid er steget.": 37,
"Fløden stiger til toppen.": 31,
"De høje bølger vil oversvømme os.": 39,
"Kassereren skal balancere sine bøger.": 40,
"Helt udsolgt af det.": 26,
"Gerningsstedets placering.": 28,
"Kansleren var meget kedelig.": 32,
"Ulykkesstedet er et helligsted for fans.": 41,
"En tumor er OK hvis den er godartet.": 36,
"Tag et bad denne måned.": 31,
"Huslejen betales i begyndelsen af måneden.": 42,
"For mord får du en lang fængselsstraf.": 41,
"Meget højere risiko for at få kræft.": 40,
"Stop mens du er foran.": 30,
"Knæbenet er forbundet med lårbenet.": 38,
"Sikkert at gå på gaderne om aftenen.": 40,
"Heldigvis blev min pung fundet.": 36,
"En time er afsat til spørgsmål.": 33,
"Så du mener du fortjener en lønforhøjelse.": 44,
"De så hele filmen.": 27,
"Gode job til dem med uddannelse.": 37,
"Springer lige ud af vandet.": 33,
"Togene er altid forsinkede.": 32,
"Sid foran i bussen.": 27,
"Foretrækker du en vinduesplads.": 33,
"Maden på denne restaurant.": 26,
"Canada har ti provinser.": 27,
"Elevatordøren ser ud til at sidde fast.": 42,
"Regndråber bliver ved med at falde på mit hoved.": 53,
"Spild kaffe på tæppet.": 27,
"En fremragende måde at kommunikere på.": 41,
"For hvert skridt fremad.": 28,
"Hurtigere end en kugle der flyver.": 36,
"Ønsketænkning er fint.": 29,
"Ingenting galt med hans stil.": 32,
"At diskutere med chefen er nytteløst.": 41,
"At tage toget er normalt hurtigere.": 39,
"Hvad der går op, må komme ned.": 34,
"Vær vedholdende for at vinde en strejke.": 42,
"Præsidenter kører dyre biler.": 33,
"Børsen faldt.": 18,
"Hvorfor stiller du tåbelige spørgsmål.": 38,
"Det er et meget grimt snit.": 33,
"Hvad man skal gøre når olien slipper op.": 44,
"Lær at gå før du løber.": 32,
"Forsikring er vigtig for dårlige bilister.": 41,
"Rejser til konferencer er sjovt.": 35,
"Bliver du nervøs når du taler.": 36,
"Pumpning hjælper hvis vejene er glatte.": 43,
"Parkeringsbøder kan bestrides.": 34,
"Lejligheder er for dyre.": 27,
"Find en parkeringsplads i nærheden.": 39,
"Krudt skal håndteres med forsigtighed.": 42,
"Lige hvad lægen ordinerede.": 33,
"En klapperslange er meget giftig.": 37,
"Piletræer findes nær vand.": 33,
"Jeg kan ikke tro jeg spiste det hele.": 40,
"Den største hamburger jeg nogensinde har set.": 48,
"Spillere taber til sidst deres skjorter.": 39,
"Motion er godt for sindet.": 32,
"Uregelmæssige verber er svære at lære.": 43,
"De kan finde din kommentar stødende.": 39,
"Sig en løgn og din næse vil vokse.": 40,
"En forstørret næse antyder at du er en løgner.": 48,
"Løgndetektor-test virker aldrig.": 35,
"Læg ikke løgn i retten eller andet.": 38,
"De fleste dommere er meget ærlige.": 37,
"Kun en idiot ville lyve i retten.": 38,
"Vigtige nyheder ser altid ud til at være forsinkede.": 50,
"Prøv at være hjemme før midnat.": 36,
"Hvis du kommer hjem sent, er dørene låst.": 44,
"Kollegie-døre låses ved midnat.": 34,
"At være oppe hele natten er en dårlig idé.": 44,
"Du er en kapitalistisk gris.": 32,
"Motiverende seminarer gør mig syg.": 38,
"At stille spørgsmålstegn ved domstolene visdom.": 46,
"Afvisningsbreve er demotiverende.": 36,
"Første gang han prøvede at svømme.": 38,
"Den folkeafstemning stillede et tåbeligt spørgsmål.": 50,
"En stejl læringskurve i at køre en enhjulet cykel.": 52,
"Et godt stimulus fortjener et godt svar.": 43,
"Alle taber i forældremyndighedssager.": 41,
"Læg affald i en forladt mine.": 34,
"Rekruttering af medarbejdere kræver stor indsats.": 47,
"Erfaring er svær at få.": 28,
"Alle ønsker at vinde i lotteriet.": 38,
"Strejkelinjen giver mig kuldegysninger.": 43,
}