export const testSentences = [
"Mit ur faldt i vandet.",
"Fremherskende vind fra øst.",
"Aldrig for rig og aldrig for tynd.",
"Det er svært at trække vejret.",
"Jeg kan se ringene på Saturn.",
"Fysik og kemi er svære.",
"Min bankkonto er overtrukket.",
"Valg frembringer det bedste.",
"Vi får spaghetti.",
"Tid til at handle ind.",
"Et problem med motoren.",
"Elefanter er bange for mus.",
"Mit yndlingssted at besøge.",
"Tre to en nul affyring.",
"Mit yndlingsfag er psykologi.",
"Forholdene er uacceptable.",
"Pas på lavtflyvende genstande.",
"Hvis du først ikke har succes.",
"Angiv venligst din fødselsdato.",
"Vi løber risikoen for at fejle.",
"Bøn i skolen støder nogle.",
"Han er ligesom alle andre.",
"Stor forstyrrelse i kraften.",
"Kærlighed betyder mange ting.",
"Du må være ved at blive gammel.",
"Verden er en scene.",
"Må jeg stå på skøjter med søster i dag.",
"Værken låner eller udlåner.",
"Et pokkers spørgsmål.",
"Et spørgsmål der må besvares.",
"Pas på ides of March.",
"Double double slid og besvær.",
"Benægtelsens kraft.",
"Jeg er enig med dig.",
"Sig ikke noget.",
"Spil den igen Sam.",
"Kraften er med dig.",
"Du er endnu ikke en jedi.",
"Et tilbud du ikke kan afslå.",
"Taler du til mig.",
"Ja du er meget klog.",
"Alt arbejde og ingen leg.",
"Hårgele er meget fedtet.",
"Valium i økonomistørrelse.",
"Fakta står i vejen.",
"Drømmernes drømmere.",
"Havde du en god tid.",
"Rummet er en høj prioritet.",
"Du er et vidunderligt eksempel.",
"Spild ikke din tid.",
"Drik ikke for meget.",
"Tag en kaffepause.",
"Popularitet ønskes af alle.",
"Musikken er bedre end den lyder.",
"Stjernelys og dugdråbe.",
"Livet er let.",
"Fiskene springer.",
"Bomulden er høj.",
"Kørte min Chevy til dæmningen.",
"Men dæmningen var tør.",
"Jeg hentede roveren fra værkstedet.",
"Film om en skør professor.",
"Kom og se vores nye bil.",
"Finder på skarpe sound bites.",
"Jeg skal til musiktime.",
"Modstanderholdet er derovre.",
"Snart vender vi hjem fra byen.",
"Jeg har slips og jakke på.",
"Den hurtige brune ræv sprang.",
"Alt sammen i en stor bunke.",
"Bær en krone med mange juveler.",
"Der kommer tåge i aften.",
"Jeg er allergisk overfor bier og peanuts.",
"Han er stadig på vores hold.",
"Dow Jones-indekset er steget.",
"Min foretrukne snack er chokolade.",
"Kongen sender dig i tårnet.",
"Vi er undersåtter og må adlyde.",
"Mor strikkede hende en rullekrave.",
"Guldlok og de tre bjørne.",
"Vi handlede dagligvarer.",
"Opgaven skal afleveres i dag.",
"Hvad du ser er hvad du får.",
"Kun til din orientering.",
"En fjerdedel af et århundrede.",
"Butikken lukker klokken ti.",
"Hoved skulder knæ og tæer.",
"Vaniljeis.",
"Ofte stillede spørgsmål.",
"Round robin-planlægning.",
"Informationsmotorvejen.",
"Min yndlingsbrowser.",
"Laserprinteren er gået i stå.",
"Alle gode drenge fortjener fudge.",
"Det næststørste land.",
"Ring for flere detaljer.",
"Lige i tid til festen.",
"Hav en god weekend.",
"Videokamera med zoomlinse.",
"Hvad en abe ser, gør en abe.",
"Det er meget uheldigt.",
"Baghaven til vores hus.",
"Det er en meget god idé.",
"Læseuge er lige på trapperne.",
"Vores faxnummer er ændret.",
"Tak for din hjælp.",
"Ingen bytte uden bon.",
"Den tidlige fugl får ormen.",
"Spænd selen for sikkerheden.",
"Det er for meget at håndtere.",
"Beskyt dit miljø.",
"Verdens befolkning vokser.",
"Biblioteket er lukket i dag.",
"Mary havde et lille lam.",
"Undervisningstjenester vil hjælpe.",
"Vi accepterer personlige checks.",
"Dette er en nonprofitorganisation.",
"Brugervenlig grænseflade.",
"Sund mad er godt for dig.",
"Praktisk erfaring med et job.",
"Dette ur er for dyrt.",
"Postvæsenet er meget langsomt.",
"Kommunikér via e-mail.",
"Hovedstaden i vores nation.",
"Rejs med lysets hastighed.",
"Jeg er ikke helt enig med dig.",
"Gasregninger sendes månedligt.",
"Jordskælv er forudsigelige.",
"Livet er kun en drøm.",
"Tag det til genbrugspladsen.",
"Send dette som anbefalet post.",
"Efterår er min yndlingsårstid.",
"En ræv er et meget klogt dyr.",
"Børnene er meget spændte.",
"Parkeringspladsen er fuld af lastbiler.",
"Min cykel har en punktering.",
"Gå ikke for hurtigt.",
"En and kvækker for mad.",
"Begrænset garanti på to år.",
"De fire årstider vil komme.",
"Solen står op i øst.",
"Det er meget blæsende i dag.",
"Vær ikke bekymret for dette.",
"Fart over feltet i sneen.",
"Vil du med os til frokost.",
"Hold dig væk fra fremmede.",
"I selskab med en voksen.",
"Vi ses senere alligator.",
"Gør min dag, din nar.",
"Jeg kan spille meget bedre nu.",
"Hun bruger for meget makeup.",
"Mit bare ansigt i vinden.",
"Batman bærer en kappe.",
"Jeg hader at bage tærter.",
"Lydia vil gerne hjem.",
"Vind førstepræmien i konkurrencen.",
"Freud skrev om jeget.",
"Jeg er ligeglad om du gør det.",
"Dæk altid alle baser.",
"Ingen bekymrer sig længere.",
"Kan vi spille kort i aften.",
"Få det væk straks.",
"Jeg så Blazing Saddles.",
"Summen af delene.",
"De elsker at snakke om ingenting.",
"Kig ud af vinduet.",
"Vær hjemme før midnat.",
"Han spillede en alfons i den film.",
"Jeg skimtede dit forslag.",
"Han havde en sweatshirt på.",
"Ingen flere krige, ingen mere blodsudgydelse.",
"Kast bolden rundt.",
"Jeg møder dig klokken tolv.",
"Jeg vil holde din hånd.",
"Børnene leger.",
"Superman bar aldrig maske.",
"Jeg lytter til båndet hver dag.",
"Han råber højt.",
"Korrigér din diktion straks.",
"Erfarne golfspillere elsker spillet.",
"Han kølede af efter hun gik.",
"Min hund fælder sit hår.",
"Kom med os på terrassen.",
"Disse småkager er fantastiske.",
"Jeg kan stadig føle din tilstedeværelse.",
"Hunden vil bide dig.",
"En helt latterlig ting.",
"Hvor fik du det slips fra.",
"Sikken en dejlig rød jakke.",
"Kan du lide at handle om søndagen.",
"Jeg spildte kaffe på tæppet.",
"Det største af de fem oceaner.",
"Skal vi spille et spil kort.",
"Olympiske atleter bruger doping.",
"Min mor bager gode småkager.",
"Gør en god gerning for nogen.",
"Hurtigt, der banker nogen.",
"Blinkende rødt lys betyder stop.",
"Udbredte forstæder er dårlige.",
"Hvor lagde jeg mine briller.",
"På vej til sommerhuset.",
"Meget klor i vandet.",
"Drik ikke vandet.",
"Min bil går altid i stykker om vinteren.",
"Julemanden sad fast.",
"Kollektiv trafik er meget hurtigere.",
"Fokuser på fakta.",
"Find på nogle flere sætninger.",
"Mine fingre er meget kolde.",
"Regn regn gå din vej.",
"Dårligt for miljøet.",
"Universiteter er for dyre.",
"Prisen på benzin er høj.",
"Vinderen af løbet.",
"Vi kører på motorveje.",
"Vi parkerer i indkørsler.",
"Tag ud efter pizza og øl.",
"Det kræver indsats.",
"Hvor kan min lille hund være.",
"Hvis du ikke var så dum.",
"Ikke helt så klog som du tror.",
"Kan du lide at campere.",
"Denne person er en katastrofe.",
"Nationens fantasi.",
"Universelt forstået som forkert.",
"Lyt til fem timers opera.",
"En lejlighedsvis bid chokolade.",
"Ofre fortjener mere erstatning.",
"Demonstranter blokerede al trafik.",
"Acceptance-talen var kedelig.",
"Arbejd hårdt for at nå toppen.",
"Der er brug for lidt opmuntring.",
"Streng straf for at komme for sent hjem.",
"Pennen er mægtigere end sværdet.",
"Overskrid den maksimale hastighedsgrænse.",
"I skarp kontrast til dine ord.",
"Denne læderjakke er for varm.",
"Konsekvenserne af en forkert drejning.",
"Denne missionserklæring er noget vrøvl.",
"Du vil miste din stemme.",
"Hvert æble fra hvert træ.",
"Er du sikker på du vil have dette.",
"Den fjerde udgave var bedre.",
"Dette system for beskatning.",
"Smukke malerier i galleriet.",
"En yard er næsten som en meter.",
"Vi glemte din fødselsdag.",
"Koalitionsregeringer virker aldrig.",
"Ødelæggelse af regnskoven.",
"Jeg kan lide at spille tennis.",
"Skarpt bevidst om hendes gode udseende.",
"Du vil spise din kage.",
"Maskiner er for komplicerede.",
"Et blik i den rigtige retning.",
"Jeg kan bare ikke finde ud af det.",
"Følg venligst retningslinjerne.",
"En lufthavn er et meget travlt sted.",
"Mysteriet om den forsvundne lagune.",
"Er der nogen indikation på dette.",
"Kamret træffer vigtige beslutninger.",
"Dette fænomen vil aldrig ske.",
"Forpligtelser skal opfyldes først.",
"Gyldig indtil årets slutning.",
"Indsend alle klager skriftligt.",
"Billetter er meget dyre.",
"Et billede siger mange ord.",
"Denne kamera tager gode billeder.",
"Det ligner en skurvogn.",
"Hunden begravede benet.",
"Den dristige unge mand.",
"Denne ligning er for kompliceret.",
"Ekspreslevering er meget hurtig.",
"Jeg tager mine briller på.",
"En touchdown i sidste minut.",
"Finansministeriet er fallit.",
"Et godt svar på spørgsmålet.",
"Godt forbundet med folk.",
"Badeværelset er godt til læsning.",
"Generationskløften bliver større.",
"Det kemiske udslip tog evigheder.",
"Forbered eksamen på forhånd.",
"En interessant observation blev gjort.",
"Banktransaktionen blev ikke registreret.",
"Din etikette kræver arbejde.",
"Vi må hellere undersøge dette.",
"Nationens stabilitet.",
"Hus med nyt elpanel.",
"Vores sølvbryllup nærmer sig.",
"Præsidentsuiten er meget travl.",
"Straffen skal passe til forbrydelsen.",
"Skarp ost holder sindet skarpt.",
"Registreringsperioden er slut.",
"Du har min medfølelse.",
"Øvelsens formål.",
"Historisk møde uden resultat.",
"Meget tilbageholdende med at gå ind.",
"God til addition og subtraktion.",
"Seks døtre og syv sønner.",
"En meget ulækker ting at sige.",
"Underskriv udbetalingsseddel.",
"Forholdene er meget anspændte.",
"Mindst mulige tid.",
"En meget traditionel måde at klæde sig på.",
"Nationens ambitioner.",
"Middelalderen var meget hård.",
"En sikkerhedsstyrke på otte tusind.",
"Der er vindere og tabere.",
"Vælgerne smed ham ud.",
"Afdrag på et huslån.",
"Det romerske riges fald.",
"Så du den spektakulære eksplosion.",
"Gem kvitteringer for alle udgifter.",
"Angrebet varede seks måneder.",
"Sæt dine prioriteter i orden.",
"Rejser kræver meget brændstof.",
"Længere end en fodboldbane.",
"En god joke fortjener et godt grin.",
"Fagforeningen vil strejke.",
"Aldrig bland religion og politik.",
"Interaktioner mellem mænd og kvinder.",
"Hvor fik du den tåbelige idé fra.",
"Det bliver solskin i morgen.",
"En psykiater vil hjælpe dig.",
"Du bør gå til lægen.",
"Du skal bestille tid.",
"Faxmaskinen er i stykker.",
"Spillere skal kende alle reglerne.",
"En hund er menneskets bedste ven.",
"Vil du komme hjem til mig.",
"Februar har en ekstra dag.",
"Føl dig ikke for dårlig over det.",
"Dette bibliotek har mange bøger.",
"Byggeriet gør det svært at rejse.",
"Han ringede syv gange.",
"Det er et meget mærkeligt spørgsmål.",
"En følelse af total frustration.",
"Vi må fordoble vores indsats.",
"Ingen kys i biblioteket.",
"Den aftale er fuld af problemer.",
"Stem efter din samvittighed.",
"Min yndlingssport er racketball.",
"Trist at høre den nyhed.",
"Pistolen gik af ved et uheld.",
"Et af de fattigste lande.",
"Algoritmen er for kompliceret.",
"Din præsentation var inspirerende.",
"Det land ejes af regeringen.",
"Ingen indbrudstyve efterlader visitkort.",
"Ilden brændte hele weekenden.",
"Hvis diplomati ikke virker.",
"Hold dette fortroligt.",
"Rationalet bag beslutningen.",
"Katten har et venligt temperament.",
"Vores husholderske laver et grundigt arbejde.",
"Hendes majestæt besøgte vores land.",
"Handicappede har brug for hensyn.",
"Disse kaserner er store nok.",
"Syng gospel og blues.",
"Han gennemgik en trippel bypass-operation.",
"Grundprincipperne i en ny organisation.",
"Kigger gennem et lille hul.",
"Løber hurtigt tør for ord.",
"Det er svært at koncentrere sig.",
"Giv mig en skefuld kaffe.",
"To eller tre kopper kaffe.",
"Som der står på dåsen: godt.",
"Virksomheder annoncerer en fusion.",
"Elbiler har brug for store brændselsceller.",
"Stikket passer ikke i stikkontakten.",
"Stoffer bør undgås.",
"Den smukkeste solnedgang.",
"Vi spiser ude i weekenden.",
"Kom ombord, skibet sejler.",
"Vandet blev målt dagligt.",
"Han så til i forbløffelse.",
"En stor ridse på bordpladen.",
"Sælgere skal nå deres månedlige kvote.",
"At redde det barn var en heroisk indsats.",
"Granit er den hårdeste af alle sten.",
"Bring gerningsmændene for retten.",
"Hver lørdag folder han tøjet.",
"Uagtsom kørsel resulterer i en bøde.",
"Mikroskoper får små ting til at se store ud.",
"En kupon til en gratis prøve.",
"Fint, men kun med måde.",
"Et fag man virkelig kan nyde.",
"Vigtigt for politiske partier.",
"Det klistermærke skal valideres.",
"Ilden rasede en hel måned.",
"Man tager aldrig for mange forholdsregler.",
"Vi har nok vidner.",
"Fagforeninger ved hvordan man organiserer sig.",
"Folk dytter meget.",
"En rettelse måtte offentliggøres.",
"Jeg kan lide barok og klassisk musik.",
"Ejeren var utilgængelig.",
"Vær diskret om dit møde.",
"Mød i morgen på toilettet.",
"Forstæder vokser overalt.",
"At ryste er en måde at holde varmen.",
"Delfiner springer højt ud af vandet.",
"Prøv at nyde din barsel.",
"Ventilationssystemet er i stykker.",
"Dinosaurer har været uddøde i evigheder.",
"En ineffektiv måde at opvarme et hus.",
"Bussen var meget overfyldt.",
"En uretfærdighed sker hver dag.",
"Kroningen var meget spændende.",
"Se i pensum for kurset.",
"Rektangulære objekter har fire sider.",
"Receptpligtig medicin kræver en seddel.",
"Isoleringen virker ikke.",
"Intet bedre end at finde en skat.",
"Vores forventede levetid er steget.",
"Fløden stiger til toppen.",
"De høje bølger vil oversvømme os.",
"Kassereren skal balancere sine bøger.",
"Helt udsolgt af det.",
"Gerningsstedets placering.",
"Kansleren var meget kedelig.",
"Ulykkesstedet er et helligsted for fans.",
"En tumor er OK hvis den er godartet.",
"Tag et bad denne måned.",
"Huslejen betales i begyndelsen af måneden.",
"For mord får du en lang fængselsstraf.",
"Meget højere risiko for at få kræft.",
"Stop mens du er foran.",
"Knæbenet er forbundet med lårbenet.",
"Sikkert at gå på gaderne om aftenen.",
"Heldigvis blev min pung fundet.",
"En time er afsat til spørgsmål.",
"Så du mener du fortjener en lønforhøjelse.",
"De så hele filmen.",
"Gode job til dem med uddannelse.",
"Springer lige ud af vandet.",
"Togene er altid forsinkede.",
"Sid foran i bussen.",
"Foretrækker du en vinduesplads.",
"Maden på denne restaurant.",
"Canada har ti provinser.",
"Elevatordøren ser ud til at sidde fast.",
"Regndråber falder på mit hoved.",
"Spild kaffe på tæppet.",
"En fremragende måde at kommunikere på.",
"Med hvert skridt fremad.",
"Hurtigere end en pistol.",
"Ønsketænkning er fint.",
"Intet galt med hans stil.",
"At skændes med chefen er nytteløst.",
"At tage toget er normalt hurtigere.",
"Hvad der går op må komme ned.",
"Vær vedholdende for at vinde en strejke.",
"Præsidenter kører i dyre biler.",
"Børsen dykkede.",
"Hvorfor stiller du dumme spørgsmål.",
"Det er et meget grimt sår.",
"Hvad skal man gøre når olien slipper op.",
"Lær at gå før du løber.",
"Forsikring er vigtigt for dårlige bilister.",
"At rejse til konferencer er sjovt.",
"Bliver du nervøs når du taler.",
"Pumpning hjælper hvis vejene er glatte.",
"P-bøder kan udfordres.",
"Lejligheder er for dyre.",
"Find en nærliggende parkeringsplads.",
"Krudt skal håndteres med forsigtighed.",
"Lige hvad lægen beordrede.",
"En klapperslange er meget giftig.",
"Grædepile findes nær vand.",
"Jeg kan ikke tro jeg spiste det hele.",
"Den største burger jeg nogensinde har set.",
"Spillere mister til sidst skjorten.",
"Motion er godt for sindet.",
"Uregelmæssige verber er sværest at lære.",
"De kan finde din kommentar stødende.",
"Fortæl en løgn og din næse vil vokse.",
"En stor næse antyder at du lyver.",
"Løgnedetektortests virker aldrig.",
"Løg ikke i retten ellers.",
"De fleste dommere er meget ærlige.",
"Kun en idiot ville lyve i retten.",
"Vigtige nyheder virker altid forsinkede.",
"Prøv at være hjemme før midnat.",
"Hvis du kommer hjem sent er dørene låst.",
"Kostskolens døre er låst ved midnat.",
"At være vågen hele natten er en dårlig idé.",
"Du er en kapitalistisk gris.",
"Motivationsseminarer gør mig syg.",
"At stille spørgsmål ved domstolenes visdom.",
"Afslag er nedslående.",
"Første gang han prøvede at svømme.",
"Den folkeafstemning stillede et dumt spørgsmål.",
"En stejl indlæringskurve på en ethjulet cykel.",
"En god stimulus fortjener et godt svar.",
"Alle taber i forældremyndighedskampe.",
"Smid affald i en forladt mine.",
"Rekruttering af medarbejdere kræver indsats.",
"Erfaring er svær at få.",
"Alle vil vinde i lotto.",
"Strejkevagten giver mig kuldegysninger."
]